In [2]:
from lightfm import LightFM
from lightfm.datasets import fetch_movielens
from lightfm.evaluation import precision_at_k, auc_score
import pandas as pd
from scipy.sparse import coo_matrix
import numpy as np
from lightfm.data import Dataset
from tqdm import tqdm
from lightfm.cross_validation import random_train_test_split
from sklearn.metrics.pairwise import cosine_similarity
import scipy.sparse as sparse
import metrics
import psycopg2
import yaml
import os
import glob

# Memories

In [3]:
users = pd.read_csv("../../data/raw/users.csv")
posts = pd.read_csv("../../data/raw/posts.csv")

In [397]:
s_p = posts
posts = posts[3:]

### свернуть

In [398]:
def age_to_group(users :pd.DataFrame, col_name: str):
    """Преобразует возраст в определенную группу например 0-18 группа возрастом от 0 до 18
    users: pd.Dataframe - датафрейм пользователей
    col_name: str - название колонки, где хранится возраст
    
    return:
        pd.DataFrame который подавался на вход, добавляет колонку группы и удаляет колонку age
    """
    if col_name in users.columns:
        groups = {"0-11": (0, 11),"12-17": (12, 17), "18-24": (18, 24), "25-34": (25, 34), "35-44": (35, 44), "45-54": (45, 54), "55-64": (55, 64), "64-100": (64, 100)}
        for group in groups:
            l, h = groups[group]
            users.loc[(l <= users[col_name]) & (users[col_name] <= h), col_name + "_group"] = group
        users = users.drop(col_name, axis=1)
        return users
    return users

In [399]:
users = age_to_group(users, "age")

In [8]:
posts

,id,user_id,description,location,tag_ids,timestamp
0,26a1ba49-b09e-4275-80c3-e27154ee07d7,2c0dcabb-8260-4b7f-81f0-92913727cada,description,location,"{717125a6-72c4-460e-8b2d-35fdc53671b8,7ead7f8b...",1.713168e+09
1,f7890ff7-c8c2-452a-8362-47371d403c5b,2c0dcabb-8260-4b7f-81f0-92913727cada,description,location,"{717125a6-72c4-460e-8b2d-35fdc53671b8,7ead7f8b...",1.713168e+09
2,6d2cb977-dc1c-4385-a21b-b9db8a6d57db,2c0dcabb-8260-4b7f-81f0-92913727cada,description,location,"{717125a6-72c4-460e-8b2d-35fdc53671b8,f1f73310...",1.713168e+09
3,8afa9da1-8a4c-4c06-9183-cf94d78dfb27,2c0dcabb-8260-4b7f-81f0-92913727cada,description,location,{717125a6-72c4-460e-8b2d-35fdc53671b8},1.713168e+09
4,8819f98e-ba40-41ce-8616-dfd663f94aff,2c0dcabb-8260-4b7f-81f0-92913727cada,dasads,NaN,,1.713437e+09
5,6648d875-e8fb-4ca7-9b56-f5aeed685484,5f0d48eb-d6b9-49a9-b0e7-eba9cd7d5d3a,KewewewAK,eweweewew,"{a87c31c6-ccd0-4a8d-86ca-3768131a211b,92f0a6ca...",1.713517e+09

In [4]:
# def sql_array_to_list()

series_tags_of_posts = posts["tag_ids"].str[1:-1].str.split(",")
series_tags_of_posts
list_str_posts_tags_unique = list(set(np.concatenate(series_tags_of_posts.values).ravel()))
list_str_posts_tags_unique

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 4 has 0 dimension(s)

In [5]:
series_tags_of_posts

0    [717125a6-72c4-460e-8b2d-35fdc53671b8, 7ead7f8...
1    [717125a6-72c4-460e-8b2d-35fdc53671b8, 7ead7f8...
2    [717125a6-72c4-460e-8b2d-35fdc53671b8, f1f7331...
3               [717125a6-72c4-460e-8b2d-35fdc53671b8]
4                                                  NaN
5    [a87c31c6-ccd0-4a8d-86ca-3768131a211b, 92f0a6c...
Name: tag_ids, dtype: object

In [417]:
posts.values

array([['8afa9da1-8a4c-4c06-9183-cf94d78dfb27',
        '2c0dcabb-8260-4b7f-81f0-92913727cada', 'description',
        'location', None, 1713167640.266993]], dtype=object)

In [401]:
p_userid_unique = posts['user_id'].unique()

In [359]:
tusers = users

In [263]:
# from sklearn.preprocessing import OneHotEncoder
# from scipy.sparse import csr_matrix, vstack



# encoder = OneHotEncoder()
# encoded_data = encoder.fit_transform([[row[1], row[3], row[4], row[5]] for row in tusers.values])
# sparse_user_features = csr_matrix(encoded_data)

In [264]:

# tmp_user = tusers
# for user in tmp_user[['gender', 'city', 'country', 'age_group']].values:
#     add_feature = []
#     for feature_idx in range(len(encoder.categories_)):
#         for type_f in encoder.categories_[feature_idx]:
#             if user[feature_idx] == type_f:
#                 add_feature.append(1)
#             else:
#                 add_feature.append(0)
#     sparse_user_features = vstack([sparse_user_features, csr_matrix(add_feature)])

In [265]:
# sparse_user_features

### Равернуть

In [392]:
dataset = Dataset()
dataset.fit_partial(users=tusers["id"],
            items=posts["id"],
            item_features=np.concatenate((list_str_posts_tags_unique, p_userid_unique)),
            user_features=np.concatenate((users['gender'].unique(), users['city'].unique(), users['country'].unique(), users['age_group'].unique())))

In [402]:
dataset.fit_partial(users=tusers["id"],
            items=posts["id"])

In [334]:
list_user_features = [(i,[g, c, cn, a]) for i,g,c,cn,a in zip(users['id'], users["gender"], users["city"], users['country'], users['age_group'])]
list_user_features

[('cc384e9c-1bd4-4b61-853b-3833a316341c', ['male', nan, nan, '0-11']),
 ('eea019ca-98a0-4383-a295-8d82676cf00c', ['female', nan, nan, '0-11']),
 ('1df9ec3c-e441-4cda-91c9-67ee73720f05', ['male', nan, nan, '0-11']),
 ('394f1153-43e0-436b-8f79-40272772853a', ['male', nan, nan, '0-11']),
 ('b01be68d-f8b4-4676-9c94-be3b25339e56',
  ['male', 'Russia', 'Krasnoyarsk', '0-11']),
 ('d30b4426-f0cb-44e4-a43c-b21aa63b7c8f',
  ['male', 'Russia', 'Krasnoyarsk', '0-11']),
 ('cf55fb2b-927a-4372-8a4b-caedaf494b5e',
  ['male', 'Russia', 'Krasnoyarsk', '0-11']),
 ('f85d20ce-9d73-4690-8758-e34220617484',
  ['male', 'Russia', 'Krasnoyarsk', '0-11']),
 ('e43b92d6-394c-48cf-92f6-8334221a7268',
  ['male', 'Russia', 'Krasnoyarsk', '0-11']),
 ('f894dbe6-dafd-44a4-a187-8a236ecaa327',
  ['male', 'Russia', 'Krasnoyarsk', '0-11']),
 ('ee4efedc-f5d4-45c9-9e44-0a1e41206f0d',
  ['male', 'Russia', 'Krasnoyarsk', '0-11']),
 ('3c0eb0d5-1e9c-4885-8308-ccce81814201',
  ['male', 'Russia', 'Krasnoyarsk', '0-11']),
 ('7dc5ddde-7724-460d-8d0d-13e994842959',
  ['male', 'Russia', 'Krasnoyarsk', '0-11']),
 ('22a6611c-c3d6-41e5-92ee-4d41cefc7e0a',
  ['male', 'Russia', 'Krasnoyarsk', '0-11']),
 ('3580ba6b-8b4e-43b5-a88c-2c532994be66',
  ['male', 'Russia', 'Krasnoyarsk', '0-11']),
 ('39badfc8-9c69-46e1-8d3a-db45c9ec454d',
  ['male', 'Russia', 'Krasnoyarsk', '0-11']),
 ('50f564d5-728d-4a64-96d6-32fd65a3fb91',
  ['male', 'Russia', 'Krasnoyarsk', '0-11']),
 ('c9c6e035-74de-4b17-82f5-a2530af4eb17',
  ['male', 'Russia', 'Krasnoyarsk', '0-11']),
 ('62112eca-3574-41a4-a547-505a31d126f9',
  ['male', 'Russia', 'Krasnoyarsk', '0-11']),
 ('2c0dcabb-8260-4b7f-81f0-92913727cada',
  ['male', 'Russia', 'Krasnoyarsk', '18-24'])]

In [373]:
from sklearn.preprocessing import MultiLabelBinarizer
from scipy.sparse import csr_matrix, hstack
# mlb = MultiLabelBinarizer()
encoded_tags = mlb.transform(series_tags_of_posts)
# mlb_user_id = MultiLabelBinarizer()
encoded_user_id = mlb_user_id.transform(
[[uid] for uid in zip(posts["user_id"])]
)
sm_item_features = hstack(
[csr_matrix(encoded_tags), csr_matrix(encoded_user_id)]
)

/home/dmitry/anaconda3/envs/rec-sys/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:900: UserWarning: unknown class(es) [32] will be ignored
  warnings.warn(

In [419]:
sm_item_features.shape

(4, 4)

In [350]:
# s_sm_item_features = sm_item_features
# sm_item_features = s_sm_item_features

In [374]:
sm_item_features

<1x4 sparse matrix of type '<class 'numpy.int64'>'
	with 1 stored elements in Compressed Sparse Row format>

In [369]:
posts

,id,user_id,description,location,tag_ids,timestamp
3,8afa9da1-8a4c-4c06-9183-cf94d78dfb27,2c0dcabb-8260-4b7f-81f0-92913727cada,description,location,{717125a6-72c4-460e-8b2d-35fdc53671b8},1.713168e+09

In [381]:
print(sm_item_features)

  (0, 0)	1
  (0, 1)	1
  (0, 3)	1
  (1, 0)	1
  (1, 1)	1
  (1, 3)	1
  (2, 0)	1
  (2, 2)	1
  (2, 3)	1
  (3, 3)	1

In [337]:
sm_user_features = dataset.build_user_features(list_user_features)
sm_user_features

<20x27 sparse matrix of type '<class 'numpy.float32'>'
	with 96 stored elements in Compressed Sparse Row format>

In [338]:
list_item_features = [(i, np.concatenate((t, [ui]))) for i,t,ui in zip(posts['id'], series_tags_of_posts, posts['user_id'])]
list_item_features

[('26a1ba49-b09e-4275-80c3-e27154ee07d7',
  array(['717125a6-72c4-460e-8b2d-35fdc53671b8',
         '7ead7f8b-eb31-4bc4-b3b2-442c8c693f36',
         '2c0dcabb-8260-4b7f-81f0-92913727cada'], dtype='<U36')),
 ('f7890ff7-c8c2-452a-8362-47371d403c5b',
  array(['717125a6-72c4-460e-8b2d-35fdc53671b8',
         '7ead7f8b-eb31-4bc4-b3b2-442c8c693f36',
         '2c0dcabb-8260-4b7f-81f0-92913727cada'], dtype='<U36')),
 ('6d2cb977-dc1c-4385-a21b-b9db8a6d57db',
  array(['717125a6-72c4-460e-8b2d-35fdc53671b8',
         'f1f73310-7ba1-433c-914c-4d47fb0948f6',
         '2c0dcabb-8260-4b7f-81f0-92913727cada'], dtype='<U36'))]

In [339]:
sm_item_features = dataset.build_item_features(list_item_features)
sm_item_features

<3x7 sparse matrix of type '<class 'numpy.float32'>'
	with 12 stored elements in Compressed Sparse Row format>

In [403]:
user_id_map, user_feature_map, item_id_map, feature_item_map = dataset.mapping()

In [404]:
LEARNING_RATE = 0.25
NO_EPOCHS = 20
NO_COMPONENTS = 20  # Number of latent factorization
ITEM_ALPHA = 1e-6   # Regularization factor for item features
USER_ALPHA = 1e-6   # Regularization factor for user features

for f in glob.glob("../../data/ratings/ratings_[0-9]*.csv"):
    ratings = pd.read_csv(str(f))
    sm_interactions, sm_weights = dataset.build_interactions(ratings[["user_id","post_id","rating"]][ratings['post_id'] != "8afa9da1-8a4c-4c06-9183-cf94d78dfb27"].values)
    user_id_map, user_feature_map, item_id_map, feature_item_map = dataset.mapping()
    

    
    model.fit_partial(interactions=sm_interactions,
            user_features=sm_user_features,
            item_features=sm_item_features,
            epochs=NO_EPOCHS)

In [422]:
users['id'].values

array(['cc384e9c-1bd4-4b61-853b-3833a316341c',
       'eea019ca-98a0-4383-a295-8d82676cf00c',
       '1df9ec3c-e441-4cda-91c9-67ee73720f05',
       '394f1153-43e0-436b-8f79-40272772853a',
       'b01be68d-f8b4-4676-9c94-be3b25339e56',
       'd30b4426-f0cb-44e4-a43c-b21aa63b7c8f',
       'cf55fb2b-927a-4372-8a4b-caedaf494b5e',
       'f85d20ce-9d73-4690-8758-e34220617484',
       'e43b92d6-394c-48cf-92f6-8334221a7268',
       'f894dbe6-dafd-44a4-a187-8a236ecaa327',
       'ee4efedc-f5d4-45c9-9e44-0a1e41206f0d',
       '3c0eb0d5-1e9c-4885-8308-ccce81814201',
       '7dc5ddde-7724-460d-8d0d-13e994842959',
       '22a6611c-c3d6-41e5-92ee-4d41cefc7e0a',
       '3580ba6b-8b4e-43b5-a88c-2c532994be66',
       '39badfc8-9c69-46e1-8d3a-db45c9ec454d',
       '50f564d5-728d-4a64-96d6-32fd65a3fb91',
       'c9c6e035-74de-4b17-82f5-a2530af4eb17',
       '62112eca-3574-41a4-a547-505a31d126f9',
       '2c0dcabb-8260-4b7f-81f0-92913727cada'], dtype=object)

In [345]:
item_id_map

{'26a1ba49-b09e-4275-80c3-e27154ee07d7': 0,
 'f7890ff7-c8c2-452a-8362-47371d403c5b': 1,
 '6d2cb977-dc1c-4385-a21b-b9db8a6d57db': 2}

In [380]:
model.predict(0, list(item_id_map.values()), user_features=sm_user_features,
            item_features=sm_item_features)

array([-0.0636096, -0.0636096, -0.9151015, -0.6055291], dtype=float32)

In [ ]:
model.pre

<20x4 sparse matrix of type '<class 'numpy.float32'>'
	with 3 stored elements in COOrdinate format>

In [ ]:
sm_interactions

<16x4 sparse matrix of type '<class 'numpy.float32'>'
	with 3 stored elements in COOrdinate format>

In [ ]:
sm_item_features

<4x8 sparse matrix of type '<class 'numpy.float32'>'
	with 15 stored elements in Compressed Sparse Row format>

In [ ]:
sm_interactions

<20x4 sparse matrix of type '<class 'numpy.float32'>'
	with 3 stored elements in COOrdinate format>

# MoviesLen

In [ ]:
ratings = pd.read_csv("../../data/ratings.dat", sep="::", engine="python")
movies = pd.read_csv("../../data/movies.dat", sep="::", engine="python")
users = pd.read_csv("../../data/users.dat", sep="::", engine="python")

In [ ]:
#Удаление не очень активных пользователей
for i in users.UserID:
    if ratings[ratings['UserID'] == i].count()['UserID'] < 100:
        ratings = ratings.drop(ratings[ratings['UserID'] == i].index)

In [ ]:
ratings = ratings.sort_values('Timestamp')

In [ ]:
movies

,MovieID,Title,Genres
0,1,Toy Story (1995),Animation|Children's|Comedy
1,2,Jumanji (1995),Adventure|Children's|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
3878,3948,Meet the Parents (2000),Comedy
3879,3949,Requiem for a Dream (2000),Drama
3880,3950,Tigerland (2000),Drama
3881,3951,Two Family House (2000),Drama
3882,3952,"Contender, The (2000)",Drama|Thriller

In [ ]:
TEST_VERY_ACTIVE = 700
TEST_MEDIUM_ACTIVE = 400
TEST_SMALL_ACTIVE = 100

#### Просмотр сколько вообще пользователей посмтрели фильмов определенное количество фильмов

In [ ]:
v_count = 0
m_count = 0
s_count = 0
v_l = []
m_l = []
s_l = []
for i in users.UserID:
    if ratings[ratings['UserID'] == i].count()['UserID'] >= TEST_VERY_ACTIVE:
        v_l.append(i)
        v_count += 1
    elif ratings[ratings['UserID'] == i].count()['UserID'] >= TEST_MEDIUM_ACTIVE:
        m_l.append(i)
        m_count += 1
    elif ratings[ratings['UserID'] == i].count()['UserID'] >= TEST_SMALL_ACTIVE:
        s_l.append(i)
        s_count += 1
print(f"very_c: {v_count} medium_c: {m_count} small_c: {s_count}")

very_c: 177 medium_c: 428 small_c: 2340

In [ ]:
ratings

         UserID  MovieID  Rating   Timestamp
1000138    6040      858       4   956703932
999873     6040      593       5   956703954
1000153    6040     2384       4   956703954
1000192    6040     2019       5   956703977
1000007    6040     1961       4   956703977
...         ...      ...     ...         ...
825793     4958     2399       1  1046454338
825438     4958     1407       5  1046454443
825731     4958     2634       3  1046454548
825724     4958     3264       4  1046454548
825603     4958     1924       4  1046454590

[847302 rows x 4 columns]

In [ ]:
def change_ratings_to_valid(c_l: list, ratings: pd.DataFrame):
    # Нужно удалить часть фильмов у пользователей и запонить их, чтобы потом оценить
    val_df = []
    median_user_rating = 0
    for i in c_l:
        for user_id in i:
            base_pref = 0
            tmp_df = []
            len_bigger_then_median = 0
            while (len_bigger_then_median < 10):
                base_pref += 10
                median_user_rating = ratings[ratings['UserID'] == user_id]['Rating'][:-base_pref].median()
                tmp_df = ratings[ratings['UserID'] == user_id][-base_pref:]
                tmp_df = tmp_df[tmp_df['Rating'] >= median_user_rating].values
                len_bigger_then_median = len(tmp_df)
            val_df.append(tmp_df)         
    print(val_df)
            # print(f"median: {median_user_rating}")
            # print(f"vals: {tmp_df}")
    return val_df

In [ ]:
val_df = change_ratings_to_valid([v_l, m_l, s_l], ratings)

[array([[       195,        950,          5, 1040956458],
       [       195,       1090,          5, 1041487792],
       [       195,       3658,          4, 1041488044],
       [       195,       1949,          5, 1041659197],
       [       195,       2587,          4, 1041665302],
       [       195,        632,          5, 1042095314],
       [       195,       3746,          5, 1043562457],
       [       195,       1254,          4, 1044552222],
       [       195,       3007,          4, 1044987990],
       [       195,       1301,          4, 1044988948]]), array([[      216,      3148,         4, 976871432],
       [      216,       198,         3, 976871432],
       [      216,      2991,         3, 976871432],
       [      216,      2502,         4, 976871457],
       [      216,      1475,         3, 976871457],
       [      216,      3107,         4, 976871482],
       [      216,       105,         3, 976871482],
       [      216,       289,         3, 976871503],
       [      216,      2528,         3, 976871537],
       [      216,      1810,         3, 976871537],
       [      216,       938,         3, 976871537],
       [      216,       647,         3, 976871537],
       [      216,      3197,         3, 976871537]]), array([[      245,       904,         4, 976830325],
       [      245,       942,         3, 976830325],
       [      245,      2206,         4, 976830325],
       [      245,      1086,         3, 976830394],
       [      245,      2467,         3, 976830394],
       [      245,      1625,         3, 976830413],
       [      245,       931,         3, 976830413],
       [      245,      1732,         3, 976830503],
       [      245,      1422,         3, 976830540],
       [      245,      1018,         3, 976830540]]), array([[       302,       3424,          4, 1014071470],
       [       302,       1148,          5, 1014071470],
       [       302,       1307,          3, 1014071548],
       [       302,       2248,          4, 1014071548],
       [       302,       1077,          4, 1014071558],
       [       302,       3911,          5, 1014071565],
       [       302,       2599,          4, 1014071610],
       [       302,       1297,          4, 1014071648],
       [       302,       1968,          4, 1014071663],
       [       302,       2000,          4, 1014071663],
       [       302,       1516,          3, 1014071704],
       [       302,       2300,          4, 1014071704],
       [       302,       3397,          5, 1014071704],
       [       302,       3317,          4, 1014071726],
       [       302,       2770,          4, 1014071774],
       [       302,       3852,          4, 1014071802]]), array([[       319,       1944,          3, 1008974914],
       [       319,       3948,          3, 1008975059],
       [       319,       3747,          3, 1008975059],
       [       319,       3272,          4, 1008975127],
       [       319,       3298,          3, 1008975723],
       [       319,       3289,          4, 1008976167],
       [       319,       3623,          3, 1008976192],
       [       319,       3783,          4, 1011922168],
       [       319,        175,          4, 1015029817],
       [       319,       2054,          3, 1015029818],
       [       319,       3788,          4, 1016590228],
       [       319,       3198,          4, 1016590228],
       [       319,       3066,          3, 1016590417],
       [       319,       3097,          3, 1040499503],
       [       319,        899,          3, 1040499503],
       [       319,       2926,          3, 1040499592]]), array([[       329,       3861,          3,  991393480],
       [       329,       3204,          3,  993848482],
       [       329,       3717,          3,  994172544],
       [       329,       3911,          3,  996083737],
       [       329,       1643,          3,  996083798],
       [       329,        272,          4,  996083832],
       [       329,        370,          3,  996111127],
       [       329,       3882,          3,  997636610],
       [       329,       2033,          3, 1013455944],
       [       329,       2303,          4, 1022190039],
       [       329,        953,          3, 1022190123],
       [       329,       3317,          4, 1040905011],
       [       329,       3536,          3, 1040905011]]), array([[      352,       193,         4, 976334246],
       [      352,        42,         5, 976334268],
       [      352,      1801,         4, 976334378],
       [      352,      3158,         4, 976334418],
       [      352,       191,         4, 976334645],
       [      352,      2293,         4, 976335072],
       [      352,      3127,         4, 976335094],
       [      352,       455,         4, 976335157],
       [      352,       228,         4, 976335199],
       [      352,      1508,         4, 976335320]]), array([[       424,       1939,          5, 1044296801],
       [       424,       3521,          4, 1044647351],
       [       424,       1226,          4, 1045580139],
       [       424,       3275,          4, 1045580783],
       [       424,       3739,          5, 1045581875],
       [       424,       2128,          4, 1045581990],
       [       424,       2770,          4, 1045582554],
       [       424,       2494,          5, 1045837566],
       [       424,       3790,          4, 1045837629],
       [       424,       3194,          4, 1046112467],
       [       424,       3535,          5, 1046112575],
       [       424,       1186,          4, 1046112684],
       [       424,       2324,          4, 1046273009]]), array([[       482,        500,          3, 1002084264],
       [       482,       3274,          3, 1002084349],
       [       482,        507,          4, 1002084392],
       [       482,        112,          3, 1002084473],
       [       482,       1485,          3, 1002084493],
       [       482,       2497,          3, 1002084623],
       [       482,       1835,          3, 1002084659],
       [       482,        237,          4, 1002084876],
       [       482,       2435,          3, 1002084906],
       [       482,       2558,          3, 1002084943],
       [       482,        168,          3, 1002085044],
       [       482,       2060,          4, 1002085144],
       [       482,        276,          3, 1002085181],
       [       482,       1882,          3, 1002085274],
       [       482,        839,          3, 1002085285],
       [       482,       3950,          4, 1011681564]]), array([[      509,      2505,         4, 976299131],
       [      509,      1483,         4, 976299152],
       [      509,      2840,         4, 976299152],
       [      509,      2026,         3, 976299152],
       [      509,      3835,         3, 976299152],
       [      509,       415,         3, 976299186],
       [      509,        92,         3, 976299237],
       [      509,       540,         3, 976299237],
       [      509,       132,         3, 976299237],
       [      509,       640,         3, 976299261]]), array([[      524,      1590,         4, 976173131],
       [      524,      1468,         4, 976173203],
       [      524,      3949,         4, 976173356],
       [      524,      3952,         4, 976173386],
       [      524,      3893,         5, 976173386],
       [      524,      1114,         4, 976173485],
       [      524,        92,         4, 976173519],
       [      524,       177,         4, 976173541],
       [      524,       433,         4, 976173572],
       [      524,       694,         4, 976173604]]), array([[       531,        553,          4, 1017185282],
       [       531,       1127,          4, 1017185318],
       [       531,        538,          4, 1017185556],
       [       531,       3540,          3, 1017185581],
       [       531,       1213,          4, 1017185633],
       [       531,        613,          3, 1017185646],
       [       531,       1912,          4, 1017185664],
       [       531,        910,          3, 1017185693],
       [       531,       3615,          4, 1017185878],
       [       531,       3882,          3, 1017185992],
       [       531,       3827,          3, 1017185992],
       [       531,       3457,          3, 1017186050],
       [       531,        543,          3, 1027554864],
       [       531,        998,          3, 1033513735],
       [       531,       3039,          3, 1033513774],
       [       531,       1422,          3, 1033514024]]), array([[       549,       3512,          4,  991839439],
       [       549,       2763,          4, 1000951946],
       [       549,       3189,          4, 1000952177],
       [       549,       3536,          4, 1000952196],
       [       549,       3324,          4, 1000952335],
       [       549,       3744,          4, 1000952388],
       [       549,       3717,          4, 1000952402],
       [       549,       3300,          4, 1000952439],
       [       549,       3897,          5, 1009314955],
       [       549,       3893,          5, 1029336997],
       [       549,       3952,          4, 1029337120],
       [       549,       3863,          4, 1029337403],
       [       549,       3354,          4, 1029337610],
       [       549,       3409,          4, 1043334126]]), array([[      550,      1721,         5, 976169748],
       [      550,      1357,         4, 976169748],
       [      550,      1302,         4, 976169748],
       [      550,      2745,         4, 976169787],
       [      550,      2132,         4, 976169822],
       [      550,       953,         4, 976169822],
       [      550,      1678,         5, 976169822],
       [      550,      1673,         4, 976169848],
       [      550,      1365,         4, 976169848],
       [      550,       281,         4, 976169878],
       [      550,      2398,         4, 976169878],
       [      550,      1660,         4, 976169986],
       [      550,        94,         5, 976170016],
       [      550,       509,         4, 976170016]]), array([[      660,      2466,         3, 976806294],
       [      660,      3389,         3, 976806294],
       [      660,       882,         3, 976806475],
       [      660,       637,         3, 976806642],
       [      660,       697,         3, 976806719],
       [      660,      2017,         3, 976806786],
       [      660,      2808,         3, 976807009],
       [      660,      1458,         3, 976807855],
       [      660,      3185,         4, 976808085],
       [      660,      3513,         4, 977925191]]), array([[       678,       3363,          4, 1025130505],
       [       678,       3214,          4, 1025130505],
       [       678,       2413,          4, 1025130543],
       [       678,        585,          4, 1025130543],
       [       678,       1206,          4, 1025130543],
       [       678,       1221,          4, 1025130596],
       [       678,       3159,          4, 1025130596],
       [       678,       1974,          4, 1025130596],
       [       678,       1282,          4, 1025130596],
       [       678,       1294,          4, 1025130640],
       [       678,       3037,          4, 1025130640],
       [       678,       2639,          4, 1025130640],
       [       678,       2143,          4, 1025130640],
       [       678,       2096,          4, 1025130678],
       [       678,       1954,          4, 1025130678],
       [       678,       3720,          4, 1025130718],
       [       678,       3950,          4, 1025130719],
       [       678,       2570,          4, 1027909375],
       [       678,       2681,          4, 1043593913]]), array([[       710,       3896,          4,  990845444],
       [       710,        180,          4,  991422639],
       [       710,       2204,          4,  991632630],
       [       710,        930,          4,  991812367],
       [       710,        928,          4,  993800643],
       [       710,       2529,          4,  995229293],
       [       710,       2532,          4,  995874676],
       [       710,       3000,          4,  996472504],
       [       710,       2206,          4,  997089031],
       [       710,       2185,          4,  997515627],
       [       710,       1218,          4,  999572231],
       [       710,       2355,          4, 1005673267],
       [       710,       2579,          4, 1013325628],
       [       710,       3328,          4, 1014701068],
       [       710,       3081,          4, 1018677355]]), array([[       752,       2401,          4, 1030992110],
       [       752,       1974,          3, 1030992989],
       [       752,       3079,          3, 1030993815],
       [       752,        322,          3, 1030993851],
       [       752,        574,          3, 1031267082],
       [       752,       2721,          3, 1035090762],
       [       752,       2243,          3, 1040164079],
       [       752,       1953,          3, 1041291429],
       [       752,       1950,          4, 1041291729],
       [       752,       1225,          3, 1042045986]]), array([[      770,       637,         3, 981706567],
       [      770,       924,         3, 982189122],
       [      770,        29,         3, 982189142],
       [      770,      1199,         3, 982641419],
       [      770,      2019,         5, 982641488],
       [      770,      3510,         5, 986969368],
       [      770,      3882,         4, 986969400],
       [      770,      3000,         5, 986969442],
       [      770,      1090,         4, 989956074],
       [      770,      3359,         3, 989956502]]), array([[       839,       3659,          4, 1004639241],
       [       839,       1186,          4, 1004639289],
       [       839,       3827,          4, 1014503579],
       [       839,       3744,          4, 1014503685],
       [       839,        741,          5, 1014504106],
       [       839,       1097,          4, 1014504176],
       [       839,       2287,          4, 1014504223],
       [       839,       1472,          4, 1045856898],
       [       839,       2357,          4, 1045856898],
       [       839,         69,          4, 1045857035],
       [       839,       3556,          4, 1045857256],
       [       839,        909,          5, 1045857499],
       [       839,        750,          5, 1045857818],
       [       839,       2280,          4, 1045857818],
       [       839,        954,          5, 1045859395]]), array([[      869,      2374,         4, 999377176],
       [      869,       267,         4, 999377176],
       [      869,       486,         4, 999377176],
       [      869,      2016,         4, 999377273],
       [      869,      1014,         5, 999377273],
       [      869,        88,         4, 999377403],
       [      869,       432,         4, 999377403],
       [      869,       603,         5, 999377403],
       [      869,       153,         4, 999377403],
       [      869,      3669,         4, 999377404]]), array([[       881,       1256,          3, 1014315504],
       [       881,       1244,          3, 1014315504],
       [       881,       3897,          3, 1014315526],
       [       881,       1276,          4, 1014315526],
       [       881,        513,          4, 1014315526],
       [       881,       1197,          4, 1014315550],
       [       881,       1269,          4, 1014315550],
       [       881,       1294,          5, 1014315550],
       [       881,       1079,          3, 1014315591],
       [       881,       3363,          3, 1014315591],
       [       881,       1968,          5, 1014315591],
       [       881,       2300,          5, 1014315617],
       [       881,       1259,          4, 1014315617],
       [       881,       2918,          5, 1014315617],
       [       881,       1288,          5, 1014315638],
       [       881,       2791,          4, 1014315665],
       [       881,       2243,          3, 1014315685],
       [       881,       2797,          4, 1014315704]]), array([[      889,      2328,         3, 975364396],
       [      889,      3838,         3, 975364396],
       [      889,      2995,         3, 975364396],
       [      889,      1342,         3, 975364396],
       [      889,      2327,         3, 975364421],
       [      889,      3661,         3, 975364421],
       [      889,      2461,         3, 975364421],
       [      889,       328,         3, 975364421],
       [      889,       397,         3, 975364444],
       [      889,      3919,         3, 975364444],
       [      889,      2107,         3, 975364472],
       [      889,      2515,         3, 975364472],
       [      889,      1862,         3, 975364472],
       [      889,      3047,         5, 975364518],
       [      889,      3713,         4, 975364518]]), array([[      1010,       2718,          3, 1013805817],
       [      1010,       2861,          2, 1013805817],
       [      1010,       2959,          4, 1013805817],
       [      1010,       3510,          3, 1013805891],
       [      1010,       3175,          3, 1013805891],
       [      1010,       2688,          2, 1013805891],
       [      1010,       2580,          3, 1013805891],
       [      1010,       3752,          2, 1013805956],
       [      1010,       2723,          2, 1013805956],
       [      1010,       2396,          4, 1013806076],
       [      1010,        904,          3, 1013960474],
       [      1010,       2336,          4, 1025688195],
       [      1010,       1284,          3, 1025688195],
       [      1010,       2693,          3, 1025688215],
       [      1010,       2712,          2, 1025688547],
       [      1010,       2133,          3, 1041477172]]), array([[      1015,       3952,          4,  991925795],
       [      1015,       2624,          4,  992721178],
       [      1015,       2594,          5,  992721216],
       [      1015,       3328,          4, 1003429520],
       [      1015,       2240,          5, 1014131810],
       [      1015,       2418,          4, 1014132023],
       [      1015,        659,          4, 1018824908],
       [      1015,       3298,          4, 1045713340],
       [      1015,       1959,          5, 1045713586],
       [      1015,       3157,          4, 1045713652],
       [      1015,       2070,          5, 1045713683]]), array([[      1019,       3535,          4, 1028574617],
       [      1019,        101,          4, 1029768543],
       [      1019,       1262,          4, 1030372424],
       [      1019,       2321,          3, 1032015091],
       [      1019,       2872,          3, 1037887820],
       [      1019,       3827,          3, 1042233125],
       [      1019,       3633,          3, 1042233207],
       [      1019,       3481,          3, 1043264669],
       [      1019,       3006,          4, 1043264770],
       [      1019,        334,          4, 1043264817],
       [      1019,        337,          3, 1043265029],
       [      1019,       1594,          4, 1043265055],
       [      1019,         12,          3, 1044908779]]), array([[      1051,       2166,          4, 1008632535],
       [      1051,       3882,          4, 1008718868],
       [      1051,       2996,          4, 1009245379],
       [      1051,       2689,          4, 1013280538],
       [      1051,        988,          4, 1013280615],
       [      1051,       2966,          5, 1013281080],
       [      1051,       2891,          4, 1018301378],
       [      1051,       2167,          4, 1022615220],
       [      1051,       1350,          4, 1035666743],
       [      1051,       1333,          4, 1035666766]]), array([[      1088,        943,          4, 1041384998],
       [      1088,       2019,          5, 1041385054],
       [      1088,       3171,          4, 1043572164],
       [      1088,       1201,          4, 1043572342],

In [ ]:
len(val_df)

2945

In [ ]:
# ratings_train = pd.read_csv("../../data/ratings_train.csv")

In [ ]:
ratings_train = ratings
for clust in tqdm(val_df):
    for row in clust:
        ratings_train = ratings_train.drop(ratings_train.loc[(ratings_train['UserID'] == row[0]) & (ratings_train['MovieID'] == row[1])].index)

100%|██████████| 2945/2945 [22:34<00:00,  2.17it/s]

In [ ]:
# ratings_train.to_csv("../data/ratings_train.csv", index=False)

In [ ]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6040 entries, 0 to 6039
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   UserID      6040 non-null   int64
 1   Gender      6040 non-null   category
 2   Age         6040 non-null   category
 3   Occupation  6040 non-null   category
 4   Zip-code    6040 non-null   category
dtypes: category(4), int64(1)
memory usage: 233.9 KB

In [ ]:
for i in users.columns[1:]:
    users[i] = users[i].astype('category')

In [ ]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6040 entries, 0 to 6039
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   UserID      6040 non-null   int64
 1   Gender      6040 non-null   category
 2   Age         6040 non-null   category
 3   Occupation  6040 non-null   category
 4   Zip-code    6040 non-null   category
dtypes: category(4), int64(1)
memory usage: 233.9 KB

In [ ]:
users

      UserID Gender Age Occupation Zip-code
0          1      F   1         10    48067
1          2      M  56         16    70072
2          3      M  25         15    55117
3          4      M  45          7    02460
4          5      M  25         20    55455
...      ...    ...  ..        ...      ...
6035    6036      F  25         15    32603
6036    6037      F  45          1    76006
6037    6038      F  56          1    14706
6038    6039      F  45          0    01060
6039    6040      M  25          6    11106

[6040 rows x 5 columns]

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from scipy.sparse import csr_matrix
encoder = OneHotEncoder()
encoded_data = encoder.fit_transform([[row[2], row[3]] for row in users.values])
sparse_user_features = csr_matrix(encoded_data)

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from scipy.sparse import csr_matrix

# Пример DataFrame с данными о фильмах


# Извлекаем текстовые данные для кодирования (в данном случае жанры)
text_data = movies['Genres']

# Инициализируем и обучаем CountVectorizer для кодирования текстовых данных
vectorizer = CountVectorizer(tokenizer=lambda x: x.split('|'))
encoded_data = vectorizer.fit_transform(text_data)

# Преобразуем разреженную матрицу в формат CSR
sparse_movies_features = csr_matrix(encoded_data)

/home/dmitry/anaconda3/envs/rec-sys/lib/python3.9/site-packages/sklearn/feature_extraction/text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

In [ ]:
# users_features = pd.get_dummies(users[['UserID', 'Gender', "Age", "Occupation", "Zip-code"]])

In [ ]:
# users_features

In [ ]:
series_genre_of_movies = movies["Genres"].str.split("|")
list_str_movie_genre_unique = list(set(np.concatenate(series_genre_of_movies).ravel()))

In [ ]:
# user_metadata = users_features.drop(columns=['UserID']).columns

In [ ]:
# user_metadata

In [ ]:
tusers = users[10:]

In [ ]:
dataset = Dataset()
dataset.fit(users=users["UserID"],
            items=movies["MovieID"],
            item_features=list_str_movie_genre_unique,
            user_features=users['Age'].unique().tolist() + users['Occupation'].unique().tolist())

In [ ]:
list_user_features = [(x,[y, z]) for x,y,z in zip(users["UserID"], users["Age"], users['Occupation'])]

In [ ]:
list_user_features

[(1, [1, 10]),
 (2, [56, 16]),
 (3, [25, 15]),
 (4, [45, 7]),
 (5, [25, 20]),
 (6, [50, 9]),
 (7, [35, 1]),
 (8, [25, 12]),
 (9, [25, 17]),
 (10, [35, 1]),
 (11, [25, 1]),
 (12, [25, 12]),
 (13, [45, 1]),
 (14, [35, 0]),
 (15, [25, 7]),
 (16, [35, 0]),
 (17, [50, 1]),
 (18, [18, 3]),
 (19, [1, 10]),
 (20, [25, 14]),
 (21, [18, 16]),
 (22, [18, 15]),
 (23, [35, 0]),
 (24, [25, 7]),
 (25, [18, 4]),
 (26, [25, 7]),
 (27, [25, 11]),
 (28, [25, 1]),
 (29, [35, 7]),
 (30, [35, 7]),
 (31, [56, 7]),
 (32, [25, 0]),
 (33, [45, 3]),
 (34, [18, 0]),
 (35, [45, 1]),
 (36, [25, 3]),
 (37, [25, 9]),
 (38, [18, 4]),
 (39, [18, 4]),
 (40, [45, 0]),
 (41, [18, 4]),
 (42, [25, 8]),
 (43, [25, 12]),
 (44, [45, 17]),
 (45, [45, 16]),
 (46, [18, 19]),
 (47, [18, 4]),
 (48, [25, 4]),
 (49, [18, 12]),
 (50, [25, 2]),
 (51, [1, 10]),
 (52, [18, 4]),
 (53, [25, 0]),
 (54, [50, 1]),
 (55, [35, 12]),
 (56, [35, 20]),
 (57, [18, 19]),
 (58, [25, 2]),
 (59, [50, 1]),
 (60, [50, 1]),
 (61, [25, 17]),
 (62, [35, 3]),
 (63, [18, 4]),
 (64, [18, 1]),
 (65, [35, 12]),
 (66, [25, 18]),
 (67, [50, 5]),
 (68, [18, 4]),
 (69, [25, 1]),
 (70, [18, 4]),
 (71, [25, 14]),
 (72, [45, 0]),
 (73, [18, 4]),
 (74, [35, 14]),
 (75, [1, 10]),
 (76, [35, 7]),
 (77, [18, 4]),
 (78, [45, 1]),
 (79, [45, 0]),
 (80, [56, 1]),
 (81, [25, 0]),
 (82, [25, 17]),
 (83, [25, 2]),
 (84, [18, 4]),
 (85, [18, 4]),
 (86, [1, 10]),
 (87, [25, 14]),
 (88, [45, 1]),
 (89, [56, 9]),
 (90, [56, 13]),
 (91, [35, 7]),
 (92, [18, 4]),
 (93, [25, 17]),
 (94, [25, 17]),
 (95, [45, 0]),
 (96, [25, 16]),
 (97, [35, 3]),
 (98, [35, 7]),
 (99, [1, 10]),
 (100, [35, 17]),
 (101, [18, 3]),
 (102, [35, 19]),
 (103, [45, 7]),
 (104, [25, 12]),
 (105, [45, 12]),
 (106, [35, 11]),
 (107, [45, 18]),
 (108, [25, 12]),
 (109, [45, 15]),
 (110, [25, 2]),
 (111, [35, 15]),
 (112, [25, 16]),
 (113, [18, 12]),
 (114, [25, 2]),
 (115, [25, 17]),
 (116, [25, 17]),
 (117, [25, 17]),
 (118, [35, 17]),
 (119, [1, 10]),
 (120, [25, 11]),
 (121, [35, 7]),
 (122, [18, 4]),
 (123, [35, 9]),
 (124, [56, 7]),
 (125, [45, 14]),
 (126, [18, 9]),
 (127, [45, 3]),
 (128, [56, 6]),
 (129, [25, 11]),
 (130, [35, 17]),
 (131, [18, 4]),
 (132, [25, 17]),
 (133, [25, 0]),
 (134, [25, 0]),
 (135, [18, 4]),
 (136, [18, 2]),
 (137, [45, 6]),
 (138, [18, 20]),
 (139, [25, 20]),
 (140, [35, 1]),
 (141, [35, 13]),
 (142, [25, 7]),
 (143, [18, 3]),
 (144, [25, 17]),
 (145, [18, 4]),
 (146, [35, 20]),
 (147, [18, 4]),
 (148, [50, 17]),
 (149, [25, 1]),
 (150, [35, 7]),
 (151, [25, 20]),
 (152, [18, 4]),
 (153, [1, 10]),
 (154, [50, 20]),
 (155, [35, 12]),
 (156, [45, 7]),
 (157, [35, 16]),
 (158, [56, 7]),
 (159, [45, 0]),
 (160, [35, 7]),
 (161, [45, 16]),
 (162, [18, 4]),
 (163, [18, 4]),
 (164, [56, 13]),
 (165, [18, 16]),
 (166, [18, 4]),
 (167, [25, 11]),
 (168, [50, 0]),
 (169, [25, 7]),
 (170, [25, 11]),
 (171, [50, 17]),
 (172, [25, 3]),
 (173, [25, 0]),
 (174, [25, 16]),
 (175, [25, 2]),
 (176, [18, 3]),
 (177, [50, 1]),
 (178, [56, 17]),
 (179, [25, 0]),
 (180, [45, 12]),
 (181, [18, 17]),
 (182, [18, 4]),
 (183, [45, 1]),
 (184, [25, 0]),
 (185, [45, 0]),
 (186, [18, 5]),
 (187, [45, 1]),
 (188, [56, 16]),
 (189, [18, 0]),
 (190, [25, 17]),
 (191, [18, 4]),
 (192, [18, 1]),
 (193, [45, 15]),
 (194, [1, 10]),
 (195, [25, 12]),
 (196, [35, 9]),
 (197, [18, 14]),
 (198, [25, 12]),
 (199, [18, 4]),
 (200, [18, 4]),
 (201, [35, 2]),
 (202, [18, 4]),
 (203, [18, 4]),
 (204, [25, 7]),
 (205, [35, 12]),
 (206, [25, 17]),
 (207, [25, 12]),
 (208, [35, 17]),
 (209, [35, 1]),
 (210, [1, 10]),
 (211, [45, 17]),
 (212, [25, 16]),
 (213, [18, 4]),
 (214, [18, 20]),
 (215, [35, 14]),
 (216, [45, 13]),
 (217, [18, 4]),
 (218, [35, 14]),
 (219, [25, 4]),
 (220, [25, 12]),
 (221, [25, 0]),
 (222, [25, 1]),
 (223, [25, 17]),
 (224, [18, 4]),
 (225, [25, 7]),
 (226, [35, 1]),
 (227, [35, 20]),
 (228, [25, 15]),
 (229, [18, 10]),
 (230, [45, 1]),
 (231, [25, 3]),
 (232, [25, 20]),
 (233, [45, 20]),
 (234, [35, 7]),
 (235, [25, 0]),
 (236, [25, 5]),
 (237, [25, 6]),
 (238, [50, 7]),
 (239, [18, 19]),
 (240, [50, 17]),
 (241, [35, 20]),
 (242, [18, 4]),
 (243, [25, 16]),
 (244, [50, 7]),
 (245, [35, 16]),
 (246, [18, 4]),
 (247, [25, 17]),
 (248, [18, 17]),
 (249, [18, 14]),
 (250, [35, 16]),
 (251, [56, 17]),
 (252, [25, 12]),
 (253, [25, 11]),
 (254, [35, 17]),
 (255, [35, 0]),
 (256, [45, 16]),
 (257, [18, 18]),
 (258, [25, 7]),
 (259, [25, 1]),
 (260, [18, 19]),
 (261, [25, 20]),
 (262, [25, 1]),
 (263, [25, 7]),
 (264, [35, 0]),
 (265, [35, 7]),
 (266, [35, 11]),
 (267, [45, 12]),
 (268, [18, 12]),
 (269, [25, 2]),
 (270, [50, 14]),
 (271, [18, 4]),
 (272, [18, 0]),
 (273, [18, 4]),
 (274, [18, 4]),
 (275, [25, 0]),
 (276, [45, 16]),
 (277, [35, 1]),
 (278, [45, 18]),
 (279, [25, 14]),
 (280, [50, 7]),
 (281, [35, 0]),
 (282, [25, 17]),
 (283, [25, 0]),
 (284, [25, 12]),
 (285, [35, 0]),
 (286, [25, 1]),
 (287, [50, 13]),
 (288, [25, 12]),
 (289, [25, 0]),
 (290, [25, 20]),
 (291, [35, 12]),
 (292, [35, 7]),
 (293, [56, 1]),
 (294, [45, 9]),
 (295, [18, 0]),
 (296, [50, 5]),
 (297, [18, 2]),
 (298, [18, 4]),
 (299, [25, 12]),
 (300, [25, 7]),
 (301, [18, 4]),
 (302, [18, 4]),
 (303, [25, 7]),
 (304, [25, 0]),
 (305, [18, 0]),
 (306, [18, 0]),
 (307, [50, 16]),
 (308, [25, 2]),
 (309, [25, 4]),
 (310, [18, 4]),
 (311, [18, 4]),
 (312, [50, 2]),
 (313, [18, 4]),
 (314, [56, 9]),
 (315, [56, 1]),
 (316, [56, 13]),
 (317, [35, 7]),
 (318, [56, 13]),
 (319, [50, 6]),
 (320, [35, 6]),
 (321, [18, 4]),
 (322, [56, 17]),
 (323, [45, 12]),
 (324, [35, 17]),
 (325, [50, 3]),
 (326, [50, 11]),
 (327, [35, 18]),
 (328, [35, 12]),
 (329, [35, 7]),
 (330, [56, 7]),
 (331, [25, 7]),
 (332, [50, 1]),
 (333, [35, 2]),
 (334, [56, 2]),
 (335, [35, 18]),
 (336, [18, 0]),
 (337, [18, 19]),
 (338, [35, 7]),
 (339, [50, 7]),
 (340, [25, 3]),
 (341, [56, 13]),
 (342, [18, 12]),
 (343, [35, 3]),
 (344, [35, 14]),
 (345, [25, 12]),
 (346, [25, 0]),
 (347, [56, 1]),
 (348, [50, 7]),
 (349, [1, 10]),
 (350, [45, 20]),
 (351, [18, 4]),
 (352, [18, 4]),
 (353, [35, 7]),
 (354, [35, 1]),
 (355, [18, 3]),
 (356, [56, 20]),
 (357, [18, 0]),
 (358, [56, 1]),
 (359, [25, 17]),
 (360, [35, 17]),
 (361, [25, 14]),
 (362, [35, 20]),
 (363, [18, 10]),
 (364, [35, 1]),
 (365, [18, 4]),
 (366, [50, 15]),
 (367, [50, 12]),
 (368, [25, 0]),
 (369, [35, 1]),
 (370, [18, 17]),
 (371, [18, 4]),
 (372, [18, 4]),
 (373, [25, 2]),
 (374, [35, 14]),
 (375, [25, 2]),
 (376, [35, 1]),
 (377, [25, 17]),
 (378, [18, 0]),
 (379, [35, 1]),
 (380, [25, 2]),
 (381, [35, 17]),
 (382, [35, 20]),
 (383, [25, 7]),
 (384, [25, 11]),
 (385, [25, 6]),
 (386, [25, 0]),
 (387, [35, 7]),
 (388, [25, 0]),
 (389, [25, 6]),
 (390, [25, 4]),
 (391, [45, 11]),
 (392, [18, 7]),
 (393, [35, 17]),
 (394, [18, 0]),
 (395, [18, 5]),
 (396, [25, 1]),
 (397, [35, 17]),
 (398, [25, 17]),
 (399, [35, 6]),
 (400, [18, 3]),
 (401, [18, 0]),
 (402, [25, 11]),
 (403, [18, 4]),
 (404, [18, 4]),
 (405, [56, 1]),
 (406, [25, 20]),
 (407, [18, 17]),
 (408, [25, 11]),
 (409, [18, 12]),
 (410, [25, 1]),
 (411, [45, 1]),
 (412, [35, 15]),
 (413, [25, 11]),
 (414, [25, 0]),
 (415, [35, 0]),
 (416, [45, 14]),
 (417, [25, 0]),
 (418, [25, 3]),
 (419, [18, 3]),
 (420, [35, 1]),
 (421, [45, 3]),
 (422, [56, 17]),
 (423, [18, 4]),
 (424, [25, 17]),
 (425, [25, 12]),
 (426, [18, 4]),
 (427, [35, 12]),
 (428, [18, 4]),
 (429, [18, 0]),
 (430, [18, 10]),
 (431, [18, 10]),
 (432, [45, 16]),
 (433, [50, 6]),
 (434, [45, 3]),
 (435, [25, 7]),
 (436, [18, 4]),
 (437, [35, 17]),
 (438, [18, 11]),
 (439, [35, 14]),
 (440, [56, 1]),
 (441, [35, 1]),
 (442, [25, 1]),
 (443, [25, 3]),
 (444, [56, 0]),
 (445, [45, 12]),
 (446, [50, 0]),
 (447, [45, 11]),
 (448, [25, 17]),
 (449, [25, 7]),
 (450, [45, 1]),
 (451, [56, 13]),
 (452, [50, 17]),
 (453, [18, 4]),
 (454, [25, 20]),
 (455, [35, 2]),
 (456, [35, 0]),
 (457, [18, 4]),
 (458, [50, 16]),
 (459, [18, 4]),
 (460, [45, 18]),
 (461, [50, 7]),
 (462, [18, 16]),
 (463, [25, 7]),
 (464, [18, 4]),
 (465, [18, 19]),
 (466, [25, 5]),
 (467, [35, 3]),
 (468, [1, 10]),
 (469, [35, 6]),
 (470, [1, 10]),
 (471, [35, 7]),
 (472, [35, 0]),
 (473, [18, 4]),
 (474, [25, 17]),
 (475, [25, 2]),
 (476, [35, 0]),
 (477, [35, 14]),
 (478, [50, 16]),
 (479, [25, 12]),
 (480, [18, 4]),
 (481, [45, 7]),
 (482, [25, 14]),
 (483, [18, 12]),
 (484, [1, 10]),
 (485, [56, 7]),
 (486, [56, 0]),
 (487, [35, 17]),
 (488, [25, 12]),
 (489, [18, 4]),
 (490, [1, 10]),
 (491, [18, 4]),
 (492, [25, 12]),
 (493, [50, 7]),
 (494, [35, 0]),
 (495, [18, 10]),
 (496, [18, 4]),
 (497, [25, 17]),
 (498, [35, 17]),
 (499, [25, 1]),
 (500, [18, 2]),
 (501, [25, 2]),
 (502, [35, 6]),
 (503, [35, 11]),
 (504, [25, 2]),
 (505, [35, 17]),
 (506, [25, 16]),
 (507, [25, 0]),
 (508, [25, 12]),
 (509, [25, 2]),
 (510, [18, 12]),
 (511, [45, 4]),
 (512, [35, 0]),
 (513, [25, 0]),
 (514, [25, 2]),
 (515, [25, 1]),
 (516, [56, 14]),
 (517, [25, 14]),
 (518, [35, 12]),
 (519, [35, 14]),
 (520, [35, 20]),
 (521, [56, 7]),
 (522, [25, 12]),
 (523, [50, 7]),
 (524, [18, 0]),
 (525, [35, 6]),
 (526, [45, 17]),
 (527, [25, 2]),
 (528, [18, 17]),
 (529, [35, 12]),
 (530, [25, 2]),
 (531, [18, 14]),
 (532, [25, 7]),
 (533, [25, 12]),
 (534, [25, 15]),
 (535, [35, 6]),
 (536, [25, 20]),
 (537, [45, 14]),
 (538, [56, 16]),
 (539, [25, 2]),
 (540, [18, 1]),
 (541, [18, 4]),
 (542, [18, 4]),
 (543, [25, 5]),
 (544, [35, 12]),
 (545, [35, 17]),
 (546, [25, 0]),
 (547, [35, 12]),
 (548, [35, 16]),
 (549, [25, 6]),
 (550, [45, 8]),
 (551, [35, 20]),
 (552, [50, 18]),
 (553, [25, 2]),
 (554, [25, 12]),
 (555, [18, 4]),
 (556, [25, 9]),
 (557, [56, 1]),
 (558, [35, 20]),
 (559, [25, 7]),
 (560, [45, 15]),
 (561, [18, 14]),
 (562, [35, 20]),
 (563, [25, 4]),
 (564, [45, 1]),
 (565, [25, 16]),
 (566, [25, 17]),
 (567, [35, 20]),
 (568, [50, 17]),
 (569, [18, 4]),
 (570, [25, 4]),
 (571, [50, 5]),
 (572, [18, 4]),
 (573, [35, 2]),
 (574, [25, 19]),
 (575, [25, 12]),
 (576, [45, 15]),
 (577, [35, 0]),
 (578, [18, 17]),
 (579, [25, 5]),
 (580, [1, 10]),
 (581, [50, 14]),
 (582, [18, 4]),
 (583, [25, 0]),
 (584, [25, 0]),
 (585, [18, 1]),
 (586, [35, 14]),
 (587, [25, 20]),
 (588, [25, 11]),
 (589, [18, 2]),
 (590, [35, 6]),
 (591, [25, 0]),
 (592, [18, 0]),
 (593, [50, 1]),
 (594, [56, 13]),
 (595, [25, 7]),
 (596, [25, 1]),
 (597, [35, 12]),
 (598, [35, 7]),
 (599, [50, 6]),
 (600, [35, 17]),
 (601, [18, 20]),
 (602, [56, 6]),
 (603, [25, 6]),
 (604, [45, 17]),
 (605, [18, 4]),
 (606, [1, 10]),
 (607, [25, 0]),
 (608, [18, 4]),
 (609, [25, 7]),
 (610, [25, 4]),
 (611, [35, 0]),
 (612, [50, 7]),
 (613, [35, 20]),
 (614, [35, 1]),
 (615, [50, 17]),
 (616, [25, 7]),
 (617, [25, 7]),
 (618, [25, 0]),
 (619, [18, 1]),
 (620, [18, 0]),
 (621, [18, 4]),
 (622, [25, 0]),
 (623, [25, 17]),
 (624, [25, 1]),
 (625, [35, 12]),
 (626, [18, 4]),
 (627, [50, 2]),
 (628, [35, 0]),
 (629, [1, 10]),
 (630, [35, 14]),
 (631, [35, 17]),
 (632, [45, 17]),
 (633, [25, 17]),
 (634, [1, 10]),
 (635, [56, 17]),
 (636, [18, 20]),
 (637, [35, 12]),
 (638, [25, 6]),
 (639, [45, 17]),
 (640, [18, 4]),
 (641, [35, 0]),
 (642, [35, 1]),
 (643, [25, 2]),
 (644, [25, 20]),
 (645, [35, 20]),
 (646, [35, 7]),
 (647, [35, 12]),
 (648, [25, 12]),
 (649, [25, 4]),
 (650, [25, 17]),
 (651, [35, 7]),
 (652, [18, 20]),
 (653, [56, 13]),
 (654, [50, 7]),
 (655, [25, 2]),
 (656, [45, 16]),
 (657, [50, 13]),
 (658, [25, 0]),
 (659, [25, 0]),
 (660, [45, 16]),
 (661, [45, 1]),
 (662, [18, 4]),
 (663, [25, 7]),
 (664, [35, 18]),
 (665, [18, 2]),
 (666, [18, 0]),
 (667, [25, 18]),
 (668, [25, 3]),
 (669, [25, 17]),
 (670, [25, 12]),
 (671, [18, 4]),
 (672, [35, 7]),
 (673, [25, 20]),
 (674, [25, 17]),
 (675, [25, 20]),
 (676, [18, 16]),
 (677, [50, 2]),
 (678, [25, 0]),
 (679, [35, 16]),
 (680, [25, 12]),
 (681, [35, 7]),
 (682, [25, 4]),
 (683, [25, 4]),
 (684, [25, 4]),
 (685, [25, 4]),
 (686, [18, 4]),
 (687, [25, 7]),
 (688, [56, 13]),
 (689, [50, 0]),
 (690, [25, 12]),
 (691, [35, 11]),
 (692, [25, 0]),
 (693, [35, 12]),
 (694, [18, 4]),
 (695, [18, 1]),
 (696, [25, 12]),
 (697, [50, 6]),
 (698, [18, 4]),
 (699, [18, 0]),
 (700, [50, 17]),
 (701, [18, 4]),
 (702, [35, 7]),
 (703, [56, 1]),
 (704, [35, 8]),
 (705, [25, 4]),
 (706, [35, 20]),
 (707, [35, 7]),
 (708, [25, 0]),
 (709, [18, 0]),
 (710, [25, 20]),
 (711, [25, 18]),
 (712, [25, 0]),
 (713, [35, 7]),
 (714, [18, 4]),
 (715, [18, 0]),
 (716, [18, 4]),
 (717, [25, 11]),
 (718, [18, 2]),
 (719, [1, 0]),
 (720, [18, 0]),
 (721, [35, 9]),
 (722, [25, 12]),
 (723, [25, 12]),
 (724, [50, 13]),
 (725, [56, 11]),
 (726, [25, 9]),
 (727, [35, 11]),
 (728, [25, 6]),
 (729, [35, 12]),
 (730, [25, 0]),
 (731, [45, 3]),
 (732, [25, 7]),
 (733, [35, 16]),
 (734, [25, 7]),
 (735, [25, 14]),
 (736, [18, 12]),
 (737, [1, 19]),
 (738, [18, 17]),
 (739, [35, 12]),
 (740, [25, 14]),
 (741, [25, 5]),
 (742, [18, 0]),
 (743, [1, 2]),
 (744, [25, 17]),
 (745, [1, 10]),
 (746, [18, 19]),
 (747, [18, 4]),
 (748, [25, 0]),
 (749, [35, 18]),
 (750, [35, 9]),
 (751, [25, 17]),
 (752, [25, 3]),
 (753, [1, 10]),
 (754, [35, 7]),
 (755, [35, 0]),
 (756, [35, 0]),
 (757, [25, 12]),
 (758, [35, 7]),
 (759, [56, 3]),
 (760, [56, 15]),
 (761, [18, 7]),
 (762, [1, 10]),
 (763, [18, 10]),
 (764, [18, 20]),
 (765, [25, 17]),
 (766, [25, 7]),
 (767, [25, 12]),
 (768, [25, 12]),
 (769, [45, 17]),
 (770, [18, 4]),
 (771, [50, 1]),
 (772, [18, 12]),
 (773, [25, 6]),
 (774, [18, 4]),
 (775, [1, 17]),
 (776, [25, 3]),
 (777, [18, 19]),
 (778, [18, 17]),
 (779, [25, 0]),
 (780, [25, 17]),
 (781, [18, 4]),
 (782, [56, 1]),
 (783, [25, 4]),
 (784, [18, 0]),
 (785, [18, 19]),
 (786, [25, 0]),
 (787, [18, 4]),
 (788, [25, 0]),
 (789, [18, 1]),
 (790, [25, 17]),
 (791, [35, 7]),
 (792, [25, 17]),
 (793, [35, 14]),
 (794, [50, 20]),
 (795, [35, 14]),
 (796, [50, 6]),
 (797, [50, 7]),
 (798, [25, 20]),
 (799, [25, 5]),
 (800, [35, 12]),
 (801, [25, 20]),
 (802, [25, 16]),
 (803, [18, 4]),
 (804, [25, 20]),
 (805, [35, 12]),
 (806, [35, 0]),
 (807, [18, 4]),
 (808, [25, 7]),
 (809, [25, 17]),
 (810, [25, 12]),
 (811, [50, 0]),
 (812, [25, 6]),
 (813, [18, 4]),
 (814, [18, 4]),
 (815, [25, 4]),
 (816, [45, 0]),
 (817, [18, 4]),
 (818, [18, 4]),
 (819, [35, 7]),
 (820, [35, 7]),
 (821, [18, 2]),
 (822, [25, 1]),
 (823, [25, 0]),
 (824, [35, 12]),
 (825, [56, 1]),
 (826, [35, 1]),
 (827, [45, 2]),
 (828, [18, 4]),
 (829, [1, 19]),
 (830, [35, 7]),
 (831, [45, 0]),
 (832, [18, 2]),
 (833, [35, 7]),
 (834, [35, 12]),
 (835, [56, 0]),
 (836, [25, 11]),
 (837, [56, 7]),
 (838, [50, 17]),
 (839, [25, 0]),
 (840, [25, 3]),
 (841, [50, 14]),
 (842, [18, 0]),
 (843, [25, 7]),
 (844, [25, 0]),
 (845, [18, 0]),
 (846, [25, 5]),
 (847, [25, 7]),
 (848, [25, 15]),
 (849, [25, 3]),
 (850, [35, 0]),
 (851, [18, 4]),
 (852, [25, 5]),
 (853, [25, 17]),
 (854, [25, 16]),
 (855, [18, 2]),
 (856, [45, 6]),
 (857, [35, 17]),
 (858, [35, 14]),
 (859, [25, 12]),
 (860, [18, 0]),
 (861, [25, 7]),
 (862, [35, 7]),
 (863, [25, 7]),
 (864, [25, 0]),
 (865, [35, 1]),
 (866, [1, 10]),
 (867, [45, 12]),
 (868, [50, 17]),
 (869, [18, 20]),
 (870, [25, 1]),
 (871, [1, 10]),
 (872, [50, 1]),
 (873, [56, 6]),
 (874, [45, 15]),
 (875, [1, 10]),
 (876, [25, 4]),
 (877, [25, 0]),
 (878, [18, 2]),
 (879, [45, 16]),
 (880, [35, 17]),
 (881, [18, 14]),
 (882, [18, 2]),
 (883, [35, 14]),
 (884, [1, 10]),
 (885, [35, 0]),
 (886, [56, 0]),
 (887, [56, 16]),
 (888, [1, 10]),
 (889, [45, 20]),
 (890, [18, 4]),
 (891, [25, 1]),
 (892, [35, 0]),
 (893, [50, 6]),
 (894, [18, 4]),
 (895, [50, 1]),
 (896, [18, 15]),
 (897, [25, 6]),
 (898, [25, 7]),
 (899, [25, 1]),
 (900, [56, 13]),
 (901, [56, 0]),
 (902, [56, 0]),
 (903, [56, 13]),
 (904, [35, 20]),
 (905, [45, 12]),
 (906, [1, 10]),
 (907, [45, 6]),
 (908, [50, 1]),
 (909, [45, 7]),
 (910, [50, 0]),
 (911, [50, 0]),
 (912, [35, 2]),
 (913, [25, 0]),
 (914, [35, 9]),
 (915, [25, 7]),
 (916, [25, 1]),
 (917, [50, 6]),
 (918, [45, 1]),
 (919, [35, 1]),
 (920, [18, 4]),
 (921, [25, 17]),
 (922, [56, 16]),
 (923, [25, 7]),
 (924, [50, 17]),
 (925, [35, 3]),
 (926, [1, 10]),
 (927, [25, 20]),
 (928, [56, 16]),
 (929, [25, 15]),
 (930, [25, 5]),
 (931, [56, 1]),
 (932, [35, 6]),
 (933, [45, 1]),
 (934, [35, 7]),
 (935, [35, 14]),
 (936, [18, 4]),
 (937, [25, 15]),
 (938, [25, 1]),
 (939, [25, 20]),
 (940, [1, 10]),
 (941, [18, 20]),
 (942, [50, 6]),
 (943, [45, 12]),
 (944, [35, 0]),
 (945, [45, 7]),
 (946, [35, 7]),
 (947, [18, 0]),
 (948, [56, 12]),
 (949, [50, 17]),
 (950, [35, 7]),
 (951, [45, 2]),
 (952, [56, 16]),
 (953, [50, 20]),
 (954, [25, 0]),
 (955, [50, 7]),
 (956, [35, 1]),
 (957, [35, 1]),
 (958, [35, 2]),
 (959, [50, 11]),
 (960, [1, 10]),
 (961, [18, 10]),
 (962, [25, 1]),
 (963, [25, 0]),
 (964, [25, 7]),
 (965, [56, 7]),
 (966, [56, 2]),
 (967, [18, 0]),
 (968, [50, 12]),
 (969, [25, 11]),
 (970, [25, 0]),
 (971, [25, 12]),
 (972, [45, 1]),
 (973, [25, 1]),
 (974, [35, 19]),
 (975, [35, 0]),
 (976, [35, 14]),
 (977, [25, 2]),
 (978, [18, 0]),
 (979, [1, 10]),
 (980, [25, 6]),
 (981, [25, 20]),
 (982, [25, 9]),
 (983, [25, 16]),
 (984, [50, 16]),
 (985, [25, 4]),
 (986, [56, 0]),
 (987, [35, 17]),
 (988, [50, 11]),
 (989, [50, 0]),
 (990, [18, 6]),
 (991, [25, 9]),
 (992, [35, 3]),
 (993, [25, 0]),
 (994, [18, 2]),
 (995, [18, 4]),
 (996, [25, 17]),
 (997, [1, 19]),
 (998, [45, 20]),
 (999, [25, 15]),
 (1000, [25, 6]),
 ...]

In [ ]:
sm_user_features = dataset.build_user_features(list_user_features)
sm_user_features

<6040x6041 sparse matrix of type '<class 'numpy.float32'>'
	with 18102 stored elements in Compressed Sparse Row format>

In [ ]:
list_item_features = [(x,y) for x,y in zip(movies["MovieID"], series_genre_of_movies)]

In [ ]:
list_item_features

[(1, ['Animation', "Children's", 'Comedy']),
 (2, ['Adventure', "Children's", 'Fantasy']),
 (3, ['Comedy', 'Romance']),
 (4, ['Comedy', 'Drama']),
 (5, ['Comedy']),
 (6, ['Action', 'Crime', 'Thriller']),
 (7, ['Comedy', 'Romance']),
 (8, ['Adventure', "Children's"]),
 (9, ['Action']),
 (10, ['Action', 'Adventure', 'Thriller']),
 (11, ['Comedy', 'Drama', 'Romance']),
 (12, ['Comedy', 'Horror']),
 (13, ['Animation', "Children's"]),
 (14, ['Drama']),
 (15, ['Action', 'Adventure', 'Romance']),
 (16, ['Drama', 'Thriller']),
 (17, ['Drama', 'Romance']),
 (18, ['Thriller']),
 (19, ['Comedy']),
 (20, ['Action']),
 (21, ['Action', 'Comedy', 'Drama']),
 (22, ['Crime', 'Drama', 'Thriller']),
 (23, ['Thriller']),
 (24, ['Drama', 'Sci-Fi']),
 (25, ['Drama', 'Romance']),
 (26, ['Drama']),
 (27, ['Drama']),
 (28, ['Romance']),
 (29, ['Adventure', 'Sci-Fi']),
 (30, ['Drama']),
 (31, ['Drama']),
 (32, ['Drama', 'Sci-Fi']),
 (33, ['Adventure', 'Romance']),
 (34, ["Children's", 'Comedy', 'Drama']),
 (35, ['Drama', 'Romance']),
 (36, ['Drama']),
 (37, ['Documentary']),
 (38, ['Comedy']),
 (39, ['Comedy', 'Romance']),
 (40, ['Drama']),
 (41, ['Drama', 'War']),
 (42, ['Action', 'Crime', 'Drama']),
 (43, ['Drama']),
 (44, ['Action', 'Adventure']),
 (45, ['Comedy', 'Drama']),
 (46, ['Drama', 'Romance']),
 (47, ['Crime', 'Thriller']),
 (48, ['Animation', "Children's", 'Musical', 'Romance']),
 (49, ['Drama', 'Romance']),
 (50, ['Crime', 'Thriller']),
 (51, ['Action', 'Drama', 'Thriller']),
 (52, ['Comedy']),
 (53, ['Drama']),
 (54, ["Children's", 'Comedy']),
 (55, ['Drama']),
 (56, ['Adventure', "Children's", 'Fantasy']),
 (57, ['Drama']),
 (58, ['Drama', 'Romance']),
 (59, ['Drama', 'Mystery']),
 (60, ['Adventure', "Children's", 'Fantasy']),
 (61, ['Drama', 'Thriller']),
 (62, ['Drama']),
 (63, ['Comedy']),
 (64, ['Comedy', 'Romance']),
 (65, ['Comedy']),
 (66, ['Sci-Fi', 'Thriller']),
 (67, ['Drama']),
 (68, ['Comedy', 'Romance']),
 (69, ['Comedy']),
 (70, ['Action', 'Comedy', 'Crime', 'Horror', 'Thriller']),
 (71, ['Action']),
 (72, ['Comedy', 'Drama']),
 (73, ['Drama', 'Musical']),
 (74, ['Drama', 'Romance']),
 (75, ['Comedy', 'Drama']),
 (76, ['Sci-Fi', 'Thriller']),
 (77, ['Documentary']),
 (78, ['Drama']),
 (79, ['Drama', 'Thriller']),
 (80, ['Drama']),
 (81, ['Crime', 'Drama', 'Romance']),
 (82, ['Drama']),
 (83, ['Drama']),
 (84, ['Comedy', 'Drama']),
 (85, ['Drama', 'Romance']),
 (86, ['Adventure', 'Drama']),
 (87, ["Children's", 'Comedy']),
 (88, ['Comedy']),
 (89, ['Action', 'Thriller']),
 (90, ['Drama']),
 (92, ['Drama', 'Thriller']),
 (93, ['Comedy', 'Romance']),
 (94, ['Drama']),
 (95, ['Action', 'Thriller']),
 (96, ['Comedy']),
 (97, ['Drama']),
 (98, ['Action', 'Thriller']),
 (99, ['Documentary']),
 (100, ['Drama', 'Thriller']),
 (101, ['Comedy']),
 (102, ['Comedy']),
 (103, ['Thriller']),
 (104, ['Comedy']),
 (105, ['Drama', 'Romance']),
 (106, ['Comedy', 'Drama']),
 (107, ['Adventure', "Children's", 'Comedy', 'Musical']),
 (108, ['Documentary']),
 (109, ['Comedy']),
 (110, ['Action', 'Drama', 'War']),
 (111, ['Drama', 'Thriller']),
 (112, ['Action', 'Adventure', 'Crime']),
 (113, ['Drama', 'Mystery']),
 (114, ['Drama']),
 (115, ['Comedy']),
 (116, ['Documentary']),
 (117, ['Crime']),
 (118, ['Comedy', 'Romance']),
 (119, ['Comedy']),
 (120, ['Drama']),
 (121, ['Drama']),
 (122, ['Comedy', 'Romance']),
 (123, ['Drama', 'Mystery', 'Romance']),
 (124, ['Drama']),
 (125, ['Comedy']),
 (126, ['Adventure', "Children's", 'Fantasy']),
 (127, ['Drama']),
 (128, ['Documentary']),
 (129, ['Comedy', 'Romance']),
 (130, ['Drama']),
 (131, ['Drama', 'Romance']),
 (132, ['Thriller']),
 (133, ['Comedy', 'Drama']),
 (134, ['Documentary']),
 (135, ['Comedy']),
 (136, ['Documentary']),
 (137, ['Documentary']),
 (138, ['Drama']),
 (139, ['Action', 'Drama']),
 (140, ['Drama', 'Romance']),
 (141, ['Comedy']),
 (142, ['Drama']),
 (143, ['Drama']),
 (144, ['Comedy']),
 (145, ['Action']),
 (146, ['Adventure', "Children's"]),
 (147, ['Drama']),
 (148, ['Drama']),
 (149, ['Crime', 'Drama', 'Thriller']),
 (150, ['Drama']),
 (151, ['Drama', 'Romance', 'War']),
 (152, ['Horror']),
 (153, ['Action', 'Adventure', 'Comedy', 'Crime']),
 (154, ['Drama']),
 (155, ['Drama', 'War']),
 (156, ['Comedy']),
 (157, ['Comedy', 'War']),
 (158, ['Adventure', "Children's"]),
 (159, ['Drama']),
 (160, ['Action', 'Adventure', 'Mystery', 'Sci-Fi']),
 (161, ['Drama', 'Thriller', 'War']),
 (162, ['Documentary']),
 (163, ['Action', 'Romance', 'Thriller']),
 (164, ['Crime', 'Film-Noir', 'Mystery', 'Thriller']),
 (165, ['Action', 'Thriller']),
 (166, ['Comedy', 'Drama']),
 (167, ['Drama']),
 (168, ['Action', 'Adventure', 'Drama', 'Romance']),
 (169, ['Adventure', "Children's", 'Drama']),
 (170, ['Action', 'Crime', 'Thriller']),
 (171, ['Comedy']),
 (172, ['Action', 'Sci-Fi', 'Thriller']),
 (173, ['Action', 'Adventure', 'Sci-Fi']),
 (174, ['Comedy']),
 (175, ['Drama']),
 (176, ['Comedy']),
 (177, ['Horror']),
 (178, ['Comedy']),
 (179, ['Drama', 'Romance']),
 (180, ['Comedy']),
 (181, ['Action', "Children's"]),
 (182, ['Drama', 'Romance']),
 (183, ['Thriller']),
 (184, ['Drama']),
 (185, ['Sci-Fi', 'Thriller']),
 (186, ['Comedy']),
 (187, ['Comedy']),
 (188, ['Horror']),
 (189, ['Comedy']),
 (190, ['Thriller']),
 (191, ['Drama']),
 (192, ['Documentary']),
 (193, ['Drama']),
 (194, ['Drama']),
 (195, ['Comedy', 'Drama', 'Romance']),
 (196, ['Horror', 'Sci-Fi']),
 (197, ['Drama']),
 (198, ['Action', 'Crime', 'Sci-Fi']),
 (199, ['Drama', 'Musical']),
 (200, ['Thriller']),
 (201, ['Drama']),
 (202, ['Drama', 'Romance']),
 (203, ['Comedy']),
 (204, ['Action']),
 (205, ['Comedy', 'Drama']),
 (206, ['Documentary']),
 (207, ['Drama', 'Romance']),
 (208, ['Action', 'Adventure']),
 (209, ['Drama']),
 (210, ['Western']),
 (211, ['Drama']),
 (212, ['Comedy']),
 (213, ['Drama']),
 (214, ['Drama']),
 (215, ['Drama', 'Romance']),
 (216, ['Comedy']),
 (217, ['Drama', 'Thriller']),
 (218, ['Comedy', 'Drama']),
 (219, ['Drama']),
 (220, ['Horror']),
 (222, ['Drama', 'Romance']),
 (223, ['Comedy']),
 (224, ['Comedy', 'Drama', 'Romance']),
 (225, ['Drama', 'Thriller']),
 (226, ['Thriller']),
 (227, ['Action']),
 (228, ['Comedy']),
 (229, ['Drama', 'Thriller']),
 (230, ['Drama', 'Thriller']),
 (231, ['Comedy']),
 (232, ['Comedy', 'Drama']),
 (233, ['Drama']),
 (234, ['Comedy']),
 (235, ['Comedy', 'Drama']),
 (236, ['Comedy', 'Romance']),
 (237, ['Comedy', 'Romance']),
 (238, ['Adventure', "Children's"]),
 (239, ['Animation', "Children's", 'Comedy', 'Romance']),
 (240, ['Thriller']),
 (241, ["Children's", 'Drama']),
 (242, ['Drama', 'Musical']),
 (243, ['Comedy']),
 (244, ['Animation', "Children's"]),
 (245, ['Crime', 'Drama']),
 (246, ['Documentary']),
 (247, ['Drama', 'Fantasy', 'Romance', 'Thriller']),
 (248, ['Comedy']),
 (249, ['Drama', 'Romance']),
 (250, ["Children's", 'Comedy']),
 (251, ['Action']),
 (252, ['Comedy', 'Romance']),
 (253, ['Drama', 'Horror']),
 (254, ['Drama']),
 (255, ['Comedy']),
 (256, ['Comedy', 'Sci-Fi']),
 (257, ['Mystery', 'Thriller']),
 (258, ['Adventure', "Children's", 'Comedy', 'Fantasy', 'Romance']),
 (259, ['Crime', 'Drama', 'Thriller']),
 (260, ['Action', 'Adventure', 'Fantasy', 'Sci-Fi']),
 (261, ['Drama']),
 (262, ["Children's", 'Drama']),
 (263, ['Drama']),
 (264, ['Drama']),
 (265, ['Drama', 'Romance']),
 (266, ['Drama', 'Romance', 'War', 'Western']),
 (267, ['Comedy']),
 (268, ['Drama']),
 (269, ['Drama']),
 (270, ['Drama', 'Romance']),
 (271, ['Drama']),
 (272, ['Drama']),
 (273, ['Drama', 'Horror']),
 (274, ['Comedy']),
 (275, ['Comedy']),
 (276, ['Comedy', 'Romance']),
 (277, ['Drama']),
 (278, ['Comedy']),
 (279, ['Drama']),
 (280, ['Drama', 'Thriller']),
 (281, ['Drama']),
 (282, ['Drama']),
 (283, ['Crime', 'Drama']),
 (284, ['Action', 'Crime']),
 (285, ['Drama', 'Horror']),
 (286, ['Action', 'Sci-Fi', 'Thriller']),
 (287, ['Comedy', 'Romance']),
 (288, ['Action', 'Thriller']),
 (289, ['Comedy', 'Romance']),
 (290, ['Crime', 'Drama']),
 (291, ['Thriller']),
 (292, ['Action', 'Drama', 'Thriller']),
 (293, ['Crime', 'Drama', 'Romance', 'Thriller']),
 (294, ['Comedy', 'Romance']),
 (295, ['Comedy', 'Romance']),
 (296, ['Crime', 'Drama']),
 (297, ['Drama']),
 (298, ['Comedy']),
 (299, ['Drama']),
 (300, ['Drama']),
 (301, ['Drama', 'Romance']),
 (302, ['Drama', 'Romance']),
 (303, ['Action', 'Adventure', 'Western']),
 (304, ['Comedy', 'Drama']),
 (305, ['Comedy']),
 (306, ['Drama']),
 (307, ['Drama']),
 (308, ['Drama']),
 (309, ['Drama']),
 (310, ['Comedy']),
 (311, ['Horror', 'Thriller']),
 (312, ['Comedy']),
 (313, ['Animation', "Children's"]),
 (314, ['Drama']),
 (315, ['Action']),
 (316, ['Action', 'Adventure', 'Sci-Fi']),
 (317, ["Children's", 'Comedy', 'Fantasy']),
 (318, ['Drama']),
 (319, ['Thriller']),
 (320, ['Film-Noir', 'Thriller']),
 (321, ['Drama']),
 (322, ['Comedy', 'Drama']),
 (324, ['Comedy']),
 (325, ['Comedy']),
 (326, ['Drama']),
 (327, ['Action', 'Comedy', 'Musical', 'Sci-Fi']),
 (328, ['Horror']),
 (329, ['Action', 'Adventure', 'Sci-Fi']),
 (330, ['Comedy', 'Horror']),
 (331, ['Drama']),
 (332, ['Horror', 'Sci-Fi']),
 (333, ['Comedy']),
 (334, ['Drama']),
 (335, ['Mystery', 'Thriller']),
 (336, ['Drama', 'War']),
 (337, ['Drama']),
 (338, ['Sci-Fi', 'Thriller']),
 (339, ['Comedy', 'Romance']),
 (340, ['Adventure', 'Drama']),
 (341, ['Drama']),
 (342, ['Comedy', 'Romance']),
 (343, ["Children's"]),
 (344, ['Comedy']),
 (345, ['Comedy', 'Drama']),
 (346, ['Drama', 'Musical']),
 (347, ['Drama']),
 (348, ['Comedy']),
 (349, ['Action', 'Adventure', 'Thriller']),
 (350, ['Drama', 'Mystery', 'Thriller']),
 (351, ['Comedy', 'Drama', 'Romance']),
 (352, ['Comedy']),
 (353, ['Action', 'Romance', 'Thriller']),
 (354, ['Drama']),
 (355, ["Children's", 'Comedy']),
 (356, ['Comedy', 'Romance', 'War']),
 (357, ['Comedy', 'Romance']),
 (358, ['Drama']),
 (359, ['Comedy', 'Drama', 'Romance']),
 (360, ['Action', 'Comedy']),
 (361, ['Drama', 'Romance']),
 (362, ['Adventure', "Children's", 'Romance']),
 (363, ['Documentary']),
 (364, ['Animation', "Children's", 'Musical']),
 (365, ['Drama']),
 (366, ['Horror']),
 (367, ['Comedy', 'Crime', 'Fantasy']),
 (368, ['Action', 'Comedy', 'Western']),
 (369, ['Drama']),
 (370, ['Comedy']),
 (371, ['Comedy', 'Drama']),
 (372, ['Comedy', 'Drama']),
 (373, ['Thriller']),
 (374, ["Children's", 'Comedy']),
 (375, ['Drama']),
 (376, ['Action', 'Thriller']),
 (377, ['Action', 'Romance', 'Thriller']),
 (378, ['Comedy', 'Romance']),
 (379, ['Action', 'Sci-Fi']),
 (380, ['Action', 'Adventure', 'Comedy', 'Romance']),
 (381, ['Drama']),
 (382, ['Drama', 'Horror']),
 (383, ['Western']),
 (384, ['Action']),
 (385, ['Drama']),
 (386, ['Drama']),
 (387, ['Action', 'Comedy']),
 (388, ['Drama']),
 (389, ['Drama', 'Romance', 'War']),
 (390, ['Action', 'Comedy', 'Drama']),
 (391, ['Crime', 'Drama']),
 (392, ['Adventure', "Children's"]),
 (393, ['Action']),
 (394, ['Action']),
 (395, ['Drama']),
 (396, ['Drama']),
 (397, ['Horror']),
 (398, ['Documentary']),
 (399, ['Drama']),
 (400, ['Drama']),
 (401, ['Action', 'Thriller']),
 (402, ['Comedy']),
 (403, ['Comedy', 'Crime', 'Drama']),
 (404, ['Documentary']),
 (405, ['Action', 'Sci-Fi']),
 (406, ['Drama']),
 (407, ['Horror', 'Thriller']),
 (408, ['Drama']),
 (409, ['Drama']),
 (410, ['Comedy']),
 (411, ['Comedy']),
 (412, ['Drama']),
 (413, ['Comedy']),
 (414, ['Comedy']),
 (415, ['Comedy', 'Thriller']),
 (416, ['Western']),
 (417, ['Comedy', 'Romance']),
 (418, ['Drama']),
 (419, ['Comedy']),
 (420, ['Action', 'Comedy']),
 (421, ['Adventure', "Children's"]),
 (422, ['Thriller']),
 (423, ['Action', 'Thriller']),
 (424, ['Drama']),
 (425, ['Drama', 'Romance']),
 (426, ['Horror', 'Sci-Fi', 'Thriller']),
 (427, ['Mystery', 'Romance', 'Thriller']),
 (428, ['Drama']),
 (429, ['Comedy']),
 (430, ['Drama']),
 (431, ['Crime', 'Drama']),
 (432, ['Comedy', 'Western']),
 (433, ['Comedy']),
 (434, ['Action', 'Adventure', 'Crime']),
 (435, ['Comedy', 'Sci-Fi']),
 (436, ['Drama', 'Thriller']),
 (437, ['Comedy']),
 (438, ['Action', 'Comedy']),
 (439, ['Drama']),
 (440, ['Comedy', 'Romance']),
 (441, ['Comedy']),
 (442, ['Action', 'Sci-Fi']),
 (443, ['Documentary']),
 (444, ['Comedy', 'Romance']),
 (445, ['Comedy']),
 (446, ['Drama', 'Romance']),
 (447, ['Comedy', 'Romance']),
 (448, ['Drama']),
 (449, ['Comedy']),
 (450, ['Comedy', 'Drama']),
 (451, ['Drama', 'Mystery', 'Romance']),
 (452, ['Drama']),
 (453, ['Comedy']),
 (454, ['Drama', 'Thriller']),
 (455, ['Adventure', "Children's", 'Drama']),
 (456, ['Drama']),
 (457, ['Action', 'Thriller']),
 (458, ['Drama', 'Western']),
 (459, ['Action']),
 (460, ['Comedy']),
 (461, ['Drama', 'Romance']),
 (462, ['Action', 'Adventure']),
 (463, ['Crime', 'Drama', 'Thriller']),
 (464, ['Action', 'Adventure', 'Crime', 'Thriller']),
 (465, ['Action', 'Drama', 'War']),
 (466, ['Action', 'Comedy', 'War']),
 (467, ['Comedy']),
 (468, ['Comedy', 'Romance']),
 (469, ['Drama', 'Romance']),
 (470, ['Comedy']),
 (471, ['Comedy', 'Romance']),
 (472, ['Comedy', 'Drama']),
 (473, ['Comedy', 'War']),
 (474, ['Action', 'Thriller']),
 (475, ['Drama']),
 (476, ['Comedy', 'Drama']),
 (477, ['Drama']),
 (478, ['Comedy']),
 (479, ['Action']),
 (480, ['Action', 'Adventure', 'Sci-Fi']),
 (481, ['Drama', 'Thriller']),
 (482, ['Thriller']),
 (483, ['Drama']),
 (484, ['Adventure', "Children's"]),
 (485, ['Action', 'Comedy']),
 (486, ['Comedy']),
 (487, ['Comedy', 'Western']),
 (488, ['Drama']),
 (489, ['Comedy']),
 (490, ['Thriller']),
 (491, ['Drama']),
 (492, ['Comedy', 'Mystery']),
 (493, ['Action', 'Crime', 'Drama']),
 (494, ['Action', 'Thriller']),
 (495, ['Drama']),
 (496, ['Comedy', 'Drama', 'Romance']),
 (497, ['Comedy', 'Romance']),
 (498, ['Drama', 'Romance']),
 (499, ['Comedy', 'Romance']),
 (500, ['Comedy']),
 (501, ['Drama']),
 (502, ['Action', "Children's"]),
 (503, ['Drama']),
 (504, ['Action', 'Sci-Fi']),
 (505, ['Comedy']),
 (506, ['Drama']),
 (507, ['Action', 'Drama']),
 (508, ['Drama']),
 (509, ['Drama', 'Romance']),
 (510, ['Drama']),
 (511, ['Action', 'Drama']),
 (512, ['Horror', 'Sci-Fi']),
 (513, ['Comedy', 'Mystery', 'Romance']),
 (514, ['Comedy']),
 (515, ['Drama']),
 (516, ['Comedy', 'Drama', 'War']),
 (517, ['Action', 'Drama', 'Mystery']),
 (518, ['Comedy']),
 (519, ['Sci-Fi', 'Thriller']),
 (520, ['Comedy']),
 (521, ['Crime', 'Thriller']),
 (522, ['Action', 'Drama']),
 (523, ['Drama']),
 (524, ['Drama']),
 (525, ['Drama']),
 (526, ['Drama']),
 (527, ['Drama', 'War']),
 (528, ['Drama']),
 (529, ['Drama']),
 (530, ['Drama']),
 (531, ["Children's", 'Drama']),
 (532, ['Comedy', 'Crime', 'Horror']),
 (533, ['Action']),
 (534, ['Drama', 'Romance']),
 (535, ['Drama']),
 (536, ['Drama']),
 (537, ['Comedy', 'Drama']),
 (538, ['Drama']),
 (539, ['Comedy', 'Romance']),
 (540, ['Thriller']),
 (541, ['Film-Noir', 'Sci-Fi']),
 (542, ['Comedy']),
 (543, ['Comedy', 'Romance', 'Thriller']),
 (544, ['Action']),
 (545, ['Drama']),
 (546, ['Action', 'Adventure', "Children's", 'Sci-Fi']),
 (547, ['Action', 'Adventure', 'Thriller']),
 (548, ['Action']),
 (549, ['Documentary']),
 (550, ['Comedy', 'Romance']),
 (551, ["Children's", 'Comedy', 'Musical']),
 (552, ['Action', 'Adventure', 'Comedy']),
 (553, ['Western']),
 (554, ['Thriller']),
 (555, ['Action', 'Crime', 'Romance']),
 (556, ['Documentary']),
 (557, ['Drama']),
 (558, ['Action', 'Adventure', 'Animation', "Children's", 'Fantasy']),
 (559, ['Comedy']),
 (560, ['Drama']),
 (561, ['Thriller']),
 (562, ['Comedy', 'Drama']),
 (563, ['Drama']),
 (564, ['Comedy']),
 (565, ['Horror']),
 (566, ['Comedy', 'Romance']),
 (567, ['Drama']),
 (568, ['Comedy', 'Drama']),
 (569, ["Children's", 'Comedy']),
 (570, ['Comedy', 'Drama']),
 (571, ['Drama']),
 (572, ['Drama']),
 (573, ['Drama']),
 (574, ['Comedy', 'Drama']),
 (575, ["Children's", 'Comedy']),
 (576, ['Comedy']),
 (577, ['Adventure', "Children's"]),
 (578, ['Drama', 'Mystery']),
 (579, ['Thriller']),
 (580, ['Drama']),
 (581, ['Documentary']),
 (582, ['Comedy']),
 (583, ['Comedy', 'Drama']),
 (584, ['Drama']),
 (585, ['Comedy']),
 (586, ["Children's", 'Comedy']),
 (587, ['Comedy', 'Romance', 'Thriller']),
 (588, ['Animation', "Children's", 'Comedy', 'Musical']),
 (589, ['Action', 'Sci-Fi', 'Thriller']),
 (590, ['Adventure', 'Drama', 'Western']),
 (591, ['Action', 'Drama', 'Thriller']),
 (592, ['Action', 'Adventure', 'Crime', 'Drama']),
 (593, ['Drama', 'Thriller']),
 (594, ['Animation', "Children's", 'Musical']),
 (595, ['Animation', "Children's", 'Musical']),
 (596, ['Animation', "Children's"]),
 (597, ['Comedy', 'Romance']),
 (598, ['Comedy']),
 (599, ['Western']),
 (600, ['Thriller']),
 (601, ['Drama']),
 (602, ['Documentary']),
 (603, ['Comedy']),
 (604, ['Documentary']),
 (605, ['Drama', 'Romance']),
 (606, ['Horror']),
 (607, ['Drama']),
 (608, ['Crime', 'Drama', 'Thriller']),
 (609, ['Adventure', "Children's"]),
 (610, ['Action', 'Adventure', 'Animation', 'Horror', 'Sci-Fi']),
 (611, ['Action', 'Horror', 'Sci-Fi']),
 (612, ['Comedy']),
 (613, ['Drama', 'Romance']),
 (614, ['Drama', 'Thriller']),
 (615, ['Drama']),
 (616, ['Animation', "Children's"]),
 (617, ['Drama']),
 (618, ['Comedy', 'Romance']),
 (619, ['Comedy']),
 (620, ['Drama']),
 (621, ['Drama']),
 (623, ['Romance']),
 (624, ['Action', 'Drama', 'Thriller']),
 (625, ['Drama']),
 (626, ['Comedy']),
 (627, ['Drama', 'Thriller']),
 (628, ['Drama', 'Thriller']),
 (629, ['Drama']),
 (630, ['Drama', 'Romance']),
 (631, ['Animation', "Children's", 'Musical']),
 (632, ['War']),
 (633, ['Comedy']),
 (634, ['Comedy']),
 (635, ['Comedy', 'Drama']),
 (636, ['Drama']),
 (637, ['Comedy']),
 (638, ['Romance']),
 (639, ['Comedy']),
 (640, ['Drama', 'Thriller']),
 (641, ['Comedy']),
 (642, ['Drama']),
 (643, ['Comedy']),
 (644, ['Comedy']),
 (645, ['Drama']),
 (647, ['Drama', 'War']),
 (648, ['Action', 'Adventure', 'Mystery']),
 (649, ['Comedy', 'Drama']),
 (650, ['Drama']),
 (651, ['Comedy']),
 (652, ['Mystery']),
 (653, ['Action', 'Adventure', 'Fantasy']),
 (654, ['Drama', 'Romance']),
 (655, ['Comedy']),
 (656, ['Comedy']),
 (657, ['Comedy', 'Drama']),
 (658, ['Drama']),
 (659, ['Crime', 'Thriller']),
 (660, ['Drama']),
 (661, ['Animation', "Children's", 'Musical']),
 (662, ['Thriller']),
 (663, ['Comedy']),
 (664, ['Comedy']),
 (665, ['War']),
 (666, ['Drama']),
 (667, ['Action']),
 (668, ['Drama']),
 (669, ['Drama']),
 (670, ['Drama']),
 (671, ['Comedy', 'Sci-Fi']),
 (672, ['Drama']),
 (673, ['Adventure', 'Animation', "Children's", 'Comedy', 'Fantasy']),
 (674, ['Adventure', 'Sci-Fi']),
 (675, ['Action', 'Drama', 'Thriller']),
 (676, ['Drama']),
 (678, ['Drama', 'Thriller']),
 (679, ['Drama']),
 (680, ['Sci-Fi']),
 (681, ['Crime']),
 (682, ['Documentary', 'Drama']),
 (683, ['Documentary']),
 (684, ['Drama']),
 (685, ['Drama']),
 (687, ['Drama', 'Romance']),
 (688, ['Action', 'Adventure', 'Comedy', 'War']),
 (690, ['Romance']),
 (691, ['Comedy', 'Romance']),
 (692, ['Action', 'Sci-Fi', 'Thriller']),
 (693, ['Drama']),
 (694, ['Action']),
 (695, ['Mystery', 'Thriller']),
 (696, ['Thriller']),
 (697, ['Drama', 'Romance']),
 (698, ['Drama']),
 (699, ['Drama']),
 (700, ['Comedy']),
 (701, ['Drama']),
 (702, ['Drama']),
 (703, ['Drama']),
 (704, ['Action', 'Adventure']),
 (705, ['Comedy']),
 (706, ['Drama']),
 (707, ['Crime', 'Film-Noir', 'Thriller']),
 (708, ['Comedy', 'Romance']),
 (709, ['Animation', "Children's"]),
 (710, ['Comedy']),
 (711, ['Adventure', "Children's"]),
 (712, ['Drama']),
 (713, ['Drama']),
 (714, ['Western']),
 (715, ['Drama']),
 (716, ['Crime']),
 (717, ['Comedy']),
 (718, ['Comedy', 'Sci-Fi']),
 (719, ['Comedy']),
 (720, ['Animation']),
 (721, ['Drama']),
 (722, ['Documentary']),
 (723, ['Drama']),
 (724, ['Drama', 'Horror']),
 (725, ['Comedy']),
 (726, ['Drama']),
 (727, ['Documentary']),
 (728, ['Comedy']),
 (729, ['Drama']),
 (730, ['Drama']),
 (731, ['Mystery', 'Thriller']),
 (732, ['Crime']),
 (733, ['Action', 'Adventure', 'Thriller']),
 (734, ['Comedy']),
 (735, ['Comedy', 'Horror']),
 (736, ['Action', 'Adventure', 'Romance', 'Thriller']),
 (737, ['Action', 'Sci-Fi']),
 (738, ['Drama']),

In [ ]:
sm_item_features = dataset.build_item_features(list_item_features)
sm_item_features

<3883x3901 sparse matrix of type '<class 'numpy.float32'>'
	with 10291 stored elements in Compressed Sparse Row format>

# 1. Обучение и тест на ratings

In [ ]:
sm_interactions, sm_weights = dataset.build_interactions(ratings[["UserID","MovieID","Rating"]].values)
sm_interactions

KeyboardInterrupt:

In [ ]:
sm_interactions

<6040x3883 sparse matrix of type '<class 'numpy.int32'>'
	with 847302 stored elements in COOrdinate format>

In [ ]:
user_id_map, user_feature_map, item_id_map, feature_item_map = dataset.mapping()

In [ ]:
sm_train_interactions, sm_test_interactions = random_train_test_split(sm_interactions, test_percentage=0.2, random_state=42)
print(f"Shape of train interactions: {sm_train_interactions.shape}")
print(f"Shape of test interactions: {sm_test_interactions.shape}")

Shape of train interactions: (6040, 3883)
Shape of test interactions: (6040, 3883)

In [ ]:
sm_train_interactions

<6040x3883 sparse matrix of type '<class 'numpy.int32'>'
	with 677841 stored elements in COOrdinate format>

In [ ]:
LEARNING_RATE = 0.25
NO_EPOCHS = 20
NO_COMPONENTS = 20  # Number of latent factorization
ITEM_ALPHA = 1e-6   # Regularization factor for item features
USER_ALPHA = 1e-6   # Regularization factor for user features

model = LightFM(loss="warp",
                no_components=NO_COMPONENTS, 
                learning_rate=LEARNING_RATE, 
                item_alpha=ITEM_ALPHA,
                user_alpha=USER_ALPHA,
                random_state=42)

model.fit_partial(interactions=sm_interactions,
          user_features=sparse_user_features,
          item_features=sm_item_features,
          epochs=NO_EPOCHS)

In [ ]:
model.fit_partial(interactions=sm_interactions,
          user_features=sm_user_features,
          item_features=sm_item_features,
          epochs=NO_EPOCHS)

KeyboardInterrupt:

## Оценка встроенными методами

In [ ]:
np_arr_prec = precision_at_k(model,
                             test_interactions=sm_test_interactions,
                             user_features=sparse_user_features,
                             item_features=sm_item_features)

In [ ]:
np_arr_prec.mean()

0.14190154

In [ ]:
test_auc = auc_score(model, sm_test_interactions, train_interactions=sm_train_interactions,user_features=sm_user_features,
                             item_features=sm_item_features, num_threads=2).mean()
print('Collaborative filtering test AUC: %s' % test_auc)

Collaborative filtering test AUC: 0.88050944

# 2. Обучение и тест на ratings_train (в котором удалены некоторые фильмы)

In [ ]:
sm_interactions, sm_weights = dataset.build_interactions(ratings_train[["UserID","MovieID","Rating"]].values)
sm_interactions

<6040x3883 sparse matrix of type '<class 'numpy.int32'>'
	with 807967 stored elements in COOrdinate format>

In [ ]:
sm_train_interactions, sm_test_interactions = random_train_test_split(sm_interactions, test_percentage=0.2, random_state=42)

In [ ]:
sparse_user_features

<20x8 sparse matrix of type '<class 'numpy.float64'>'
	with 80 stored elements in Compressed Sparse Row format>

In [ ]:
user_id_map, user_feature_map, item_id_map, feature_item_map = dataset.mapping()

In [ ]:
LEARNING_RATE = 0.25
NO_EPOCHS = 20
NO_COMPONENTS = 20  # Number of latent factorization
ITEM_ALPHA = 1e-6   # Regularization factor for item features
USER_ALPHA = 1e-6   # Regularization factor for user features

model = LightFM(loss="warp",
                no_components=NO_COMPONENTS, 
                learning_rate=LEARNING_RATE, 
                item_alpha=ITEM_ALPHA,
                user_alpha=USER_ALPHA,
                random_state=42)

model.fit(interactions=sm_train_interactions,
          user_features=sparse_user_features,
          item_features=sparse_movies_features,
          epochs=NO_EPOCHS)

### Получение матрицы схожести элементов

In [ ]:
_, np_item_embeddings = model.get_item_representations(features=sparse_movies_features)
print(np_item_embeddings.shape)   # (352, 20)
np_item_embeddings[:2]

(3883, 20)

array([[-3.9402154e-01, -1.2367530e+00, -1.7833997e+00,  1.0649457e+00,
        -6.4317220e-01,  2.3647473e+00, -4.6021447e+00, -2.3143704e+00,
         8.9453125e-01, -2.0062921e+00, -8.2384479e-01,  1.6906636e+00,
         1.7190988e+00, -1.2276769e+00, -6.3924110e-01,  2.2970347e+00,
         1.2670162e+00,  3.1046448e+00,  5.2146148e-04, -1.3436410e+00],
       [ 2.0718361e+01, -6.5617018e+00,  9.1495705e+00, -1.8356833e+01,
         7.9756055e+00, -9.8699923e+00,  1.1630819e+01,  6.3855548e+00,
        -6.8139110e+00,  9.1963997e+00,  1.0331884e+01, -9.4827652e+00,
        -7.7789860e+00,  4.9694796e+00, -2.4231088e-01, -1.1948149e+01,
        -5.8588405e+00, -1.9772484e+01, -2.1357353e+00, -2.7670987e+00]],
      dtype=float32)

In [ ]:
np_item_similarities = cosine_similarity(sparse.csr_matrix(np_item_embeddings)) #сама матрица схожестей
print(np_item_similarities.shape)   # (352, 352)
np_item_similarities[:2]

(3883, 3883)

array([[ 0.9999999 , -0.7437953 ,  0.12326343, ..., -0.2740068 ,
        -0.2740068 , -0.04316745],
       [-0.7437953 ,  0.99999994, -0.00770278, ...,  0.1631929 ,
         0.1631929 , -0.28414106]], dtype=float32)

In [ ]:
df_item_similarities = pd.DataFrame(np_item_similarities)
df_item_similarities.columns = item_id_map.keys()
df_item_similarities.index = item_id_map.keys()
df_item_similarities

,1,2,3,4,5,6,7,8,9,10,...,3943,3944,3945,3946,3947,3948,3949,3950,3951,3952
1,1.000000,-0.743795,0.123263,-0.191892,-0.053089,0.817160,0.123263,0.982228,0.271390,0.629927,...,-0.053089,-0.191892,0.993774,0.180409,0.084428,-0.053089,-0.274007,-0.274007,-0.274007,-0.043167
2,-0.743795,1.000000,-0.007703,-0.243948,-0.373155,-0.989516,-0.007703,-0.617913,0.324863,-0.216175,...,-0.373155,-0.243948,-0.671229,-0.009137,-0.345165,-0.373155,0.163193,0.163193,0.163193,-0.284141
3,0.123263,-0.007703,1.000000,0.225402,0.528720,0.088248,1.000000,0.119477,-0.024009,0.568660,...,0.528720,0.225402,0.101440,0.514335,0.734912,0.528720,-0.458604,-0.458604,-0.458604,0.551490
4,-0.191892,-0.243948,0.225402,1.000000,0.849464,0.213775,0.225402,-0.309948,-0.503542,-0.028799,...,0.849464,1.000000,-0.272917,0.455209,0.637659,0.849464,0.469330,0.469330,0.469330,0.895921
5,-0.053089,-0.373155,0.528720,0.849464,1.000000,0.363707,0.528720,-0.196481,-0.452968,0.212790,...,1.000000,0.849464,-0.147933,0.532649,0.918853,1.000000,-0.067245,-0.067245,-0.067245,0.933132
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3948,-0.053089,-0.373155,0.528720,0.849464,1.000000,0.363707,0.528720,-0.196481,-0.452968,0.212790,...,1.000000,0.849464,-0.147933,0.532649,0.918853,1.000000,-0.067245,-0.067245,-0.067245,0.933132
3949,-0.274007,0.163193,-0.458604,0.469330,-0.067245,-0.204437,-0.458604,-0.257274,-0.194110,-0.410564,...,-0.067245,0.469330,-0.268497,-0.030631,-0.331950,-0.067245,1.000000,1.000000,1.000000,0.132505
3950,-0.274007,0.163193,-0.458604,0.469330,-0.067245,-0.204437,-0.458604,-0.257274,-0.194110,-0.410564,...,-0.067245,0.469330,-0.268497,-0.030631,-0.331950,-0.067245,1.000000,1.000000,1.000000,0.132505
3951,-0.274007,0.163193,-0.458604,0.469330,-0.067245,-0.204437,-0.458604,-0.257274,-0.194110,-0.410564,...,-0.067245,0.469330,-0.268497,-0.030631,-0.331950,-0.067245,1.000000,1.000000,1.000000,0.132505
3952,-0.043167,-0.284141,0.551490,0.895921,0.933132,0.289960,0.551490,-0.149925,-0.383416,0.276300,...,0.933132,0.895921,-0.124152,0.654342,0.890994,0.933132,0.132505,0.132505,0.132505,1.000000

Суть в том что, для того чтобы брать tp fp нужно будет как-то разграничивать классификацию. Если предсказанный фильм похож на один из фильмов тестовой выборки (выше определенного порога), то это положительный класс. Если он положительный, но не входит в тестовый набор, то это FN, а если входит то будет FP.

#### Нужно получить матрицу в которой будут id пользователя и фильмы, которые он не видел

In [ ]:
SIM_K = 0.7
K_TO_PRED = 100
TAKE_FIRST_PREDICT = 100

In [ ]:
test = []
for clust_idx in range(len(val_df)):
    test.append({"UserID": val_df[clust_idx][0][0], "TestMovies": [], "NoWatched": [], "UserIdMap": {val_df[clust_idx][0][0]: user_id_map[val_df[clust_idx][0][0]]}, "ItemIdMap": {}})
    for row in val_df[clust_idx]:
        test[clust_idx]['TestMovies'].append(row[1])
        test[clust_idx]['ItemIdMap'][row[1]] = item_id_map[row[1]]
test

[{'UserID': 195,
  'TestMovies': [950, 1090, 3658, 1949, 2587, 632, 3746, 1254, 3007, 1301],
  'NoWatched': [],
  'UserIdMap': {195: 194},
  'ItemIdMap': {950: 938,
   1090: 1074,
   3658: 3589,
   1949: 1880,
   2587: 2518,
   632: 627,
   3746: 3677,
   1254: 1234,
   3007: 2938,
   1301: 1281}},
 {'UserID': 216,
  'TestMovies': [3148,
   198,
   2991,
   2502,
   1475,
   3107,
   105,
   289,
   2528,
   1810,
   938,
   647,
   3197],
  'NoWatched': [],
  'UserIdMap': {216: 215},
  'ItemIdMap': {3148: 3079,
   198: 196,
   2991: 2922,
   2502: 2433,
   1475: 1447,
   3107: 3038,
   105: 103,
   289: 286,
   2528: 2459,
   1810: 1746,
   938: 926,
   647: 641,
   3197: 3128}},
 {'UserID': 245,
  'TestMovies': [904, 942, 2206, 1086, 2467, 1625, 931, 1732, 1422, 1018],
  'NoWatched': [],
  'UserIdMap': {245: 244},
  'ItemIdMap': {904: 892,
   942: 930,
   2206: 2137,
   1086: 1070,
   2467: 2398,
   1625: 1582,
   931: 919,
   1732: 1683,
   1422: 1398,
   1018: 1005}},
 {'UserID': 302,
  'TestMovies': [3424,
   1148,
   1307,
   2248,
   1077,
   3911,
   2599,
   1297,
   1968,
   2000,
   1516,
   2300,
   3397,
   3317,
   2770,
   3852],
  'NoWatched': [],
  'UserIdMap': {302: 301},
  'ItemIdMap': {3424: 3355,
   1148: 1132,
   1307: 1287,
   2248: 2179,
   1077: 1061,
   3911: 3841,
   2599: 2530,
   1297: 1277,
   1968: 1899,
   2000: 1931,
   1516: 1481,
   2300: 2231,
   3397: 3328,
   3317: 3248,
   2770: 2701,
   3852: 3782}},
 {'UserID': 319,
  'TestMovies': [1944,
   3948,
   3747,
   3272,
   3298,
   3289,
   3623,
   3783,
   175,
   2054,
   3788,
   3198,
   3066,
   3097,
   899,
   2926],
  'NoWatched': [],
  'UserIdMap': {319: 318},
  'ItemIdMap': {1944: 1875,
   3948: 3878,
   3747: 3678,
   3272: 3203,
   3298: 3229,
   3289: 3220,
   3623: 3554,
   3783: 3714,
   175: 173,
   2054: 1985,
   3788: 3719,
   3198: 3129,
   3066: 2997,
   3097: 3028,
   899: 887,
   2926: 2857}},
 {'UserID': 329,
  'TestMovies': [3861,
   3204,
   3717,
   3911,
   1643,
   272,
   370,
   3882,
   2033,
   2303,
   953,
   3317,
   3536],
  'NoWatched': [],
  'UserIdMap': {329: 328},
  'ItemIdMap': {3861: 3791,
   3204: 3135,
   3717: 3648,
   3911: 3841,
   1643: 1597,
   272: 269,
   370: 366,
   3882: 3812,
   2033: 1964,
   2303: 2234,
   953: 941,
   3317: 3248,
   3536: 3467}},
 {'UserID': 352,
  'TestMovies': [193, 42, 1801, 3158, 191, 2293, 3127, 455, 228, 1508],
  'NoWatched': [],
  'UserIdMap': {352: 351},
  'ItemIdMap': {193: 191,
   42: 41,
   1801: 1740,
   3158: 3089,
   191: 189,
   2293: 2224,
   3127: 3058,
   455: 451,
   228: 225,
   1508: 1474}},
 {'UserID': 424,
  'TestMovies': [1939,
   3521,
   1226,
   3275,
   3739,
   2128,
   2770,
   2494,
   3790,
   3194,
   3535,
   1186,
   2324],
  'NoWatched': [],
  'UserIdMap': {424: 423},
  'ItemIdMap': {1939: 1870,
   3521: 3452,
   1226: 1208,
   3275: 3206,
   3739: 3670,
   2128: 2059,
   2770: 2701,
   2494: 2425,
   3790: 3721,
   3194: 3125,
   3535: 3466,
   1186: 1169,
   2324: 2255}},
 {'UserID': 482,
  'TestMovies': [500,
   3274,
   507,
   112,
   1485,
   2497,
   1835,
   237,
   2435,
   2558,
   168,
   2060,
   276,
   1882,
   839,
   3950],
  'NoWatched': [],
  'UserIdMap': {482: 481},
  'ItemIdMap': {500: 496,
   3274: 3205,
   507: 503,
   112: 110,
   1485: 1455,
   2497: 2428,
   1835: 1767,
   237: 234,
   2435: 2366,
   2558: 2489,
   168: 166,
   2060: 1991,
   276: 273,
   1882: 1813,
   839: 828,
   3950: 3880}},
 {'UserID': 509,
  'TestMovies': [2505, 1483, 2840, 2026, 3835, 415, 92, 540, 132, 640],
  'NoWatched': [],
  'UserIdMap': {509: 508},
  'ItemIdMap': {2505: 2436,
   1483: 1453,
   2840: 2771,
   2026: 1957,
   3835: 3765,
   415: 411,
   92: 90,
   540: 536,
   132: 130,
   640: 635}},
 {'UserID': 524,
  'TestMovies': [1590, 1468, 3949, 3952, 3893, 1114, 92, 177, 433, 694],
  'NoWatched': [],
  'UserIdMap': {524: 523},
  'ItemIdMap': {1590: 1549,
   1468: 1441,
   3949: 3879,
   3952: 3882,
   3893: 3823,
   1114: 1098,
   92: 90,
   177: 175,
   433: 429,
   694: 685}},
 {'UserID': 531,
  'TestMovies': [553,
   1127,
   538,
   3540,
   1213,
   613,
   1912,
   910,
   3615,
   3882,
   3827,
   3457,
   543,
   998,
   3039,
   1422],
  'NoWatched': [],
  'UserIdMap': {531: 530},
  'ItemIdMap': {553: 549,
   1127: 1111,
   538: 534,
   3540: 3471,
   1213: 1195,
   613: 609,
   1912: 1843,
   910: 898,
   3615: 3546,
   3882: 3812,
   3827: 3757,
   3457: 3388,
   543: 539,
   998: 985,
   3039: 2970,
   1422: 1398}},
 {'UserID': 549,
  'TestMovies': [3512,
   2763,
   3189,
   3536,
   3324,
   3744,
   3717,
   3300,
   3897,
   3893,
   3952,
   3863,
   3354,
   3409],
  'NoWatched': [],
  'UserIdMap': {549: 548},
  'ItemIdMap': {3512: 3443,
   2763: 2694,
   3189: 3120,
   3536: 3467,
   3324: 3255,
   3744: 3675,
   3717: 3648,
   3300: 3231,
   3897: 3827,
   3893: 3823,
   3952: 3882,
   3863: 3793,
   3354: 3285,
   3409: 3340}},
 {'UserID': 550,
  'TestMovies': [1721,
   1357,
   1302,
   2745,
   2132,
   953,
   1678,
   1673,
   1365,
   281,
   2398,
   1660,
   94,
   509],
  'NoWatched': [],
  'UserIdMap': {550: 549},
  'ItemIdMap': {1721: 1672,
   1357: 1336,
   1302: 1282,
   2745: 2676,
   2132: 2063,
   953: 941,
   1678: 1632,
   1673: 1627,
   1365: 1344,
   281: 278,
   2398: 2329,
   1660: 1614,
   94: 92,
   509: 505}},
 {'UserID': 660,
  'TestMovies': [2466, 3389, 882, 637, 697, 2017, 2808, 1458, 3185, 3513],
  'NoWatched': [],
  'UserIdMap': {660: 659},
  'ItemIdMap': {2466: 2397,
   3389: 3320,
   882: 871,
   637: 632,
   697: 688,
   2017: 1948,
   2808: 2739,
   1458: 1431,
   3185: 3116,
   3513: 3444}},
 {'UserID': 678,
  'TestMovies': [3363,
   3214,
   2413,
   585,
   1206,
   1221,
   3159,
   1974,
   1282,
   1294,
   3037,
   2639,
   2143,
   2096,
   1954,
   3720,
   3950,
   2570,
   2681],
  'NoWatched': [],
  'UserIdMap': {678: 677},
  'ItemIdMap': {3363: 3294,
   3214: 3145,
   2413: 2344,
   585: 581,
   1206: 1188,
   1221: 1203,
   3159: 3090,
   1974: 1905,
   1282: 1262,
   1294: 1274,
   3037: 2968,
   2639: 2570,
   2143: 2074,
   2096: 2027,
   1954: 1885,
   3720: 3651,
   3950: 3880,
   2570: 2501,
   2681: 2612}},
 {'UserID': 710,
  'TestMovies': [3896,
   180,
   2204,
   930,
   928,
   2529,
   2532,
   3000,
   2206,
   2185,
   1218,
   2355,
   2579,
   3328,
   3081],
  'NoWatched': [],
  'UserIdMap': {710: 709},
  'ItemIdMap': {3896: 3826,
   180: 178,
   2204: 2135,
   930: 918,
   928: 916,
   2529: 2460,
   2532: 2463,
   3000: 2931,
   2206: 2137,
   2185: 2116,
   1218: 1200,
   2355: 2286,
   2579: 2510,
   3328: 3259,
   3081: 3012}},
 {'UserID': 752,
  'TestMovies': [2401, 1974, 3079, 322, 574, 2721, 2243, 1953, 1950, 1225],
  'NoWatched': [],
  'UserIdMap': {752: 751},
  'ItemIdMap': {2401: 2332,
   1974: 1905,
   3079: 3010,
   322: 319,
   574: 570,
   2721: 2652,
   2243: 2174,
   1953: 1884,
   1950: 1881,
   1225: 1207}},
 {'UserID': 770,
  'TestMovies': [637, 924, 29, 1199, 2019, 3510, 3882, 3000, 1090, 3359],
  'NoWatched': [],
  'UserIdMap': {770: 769},
  'ItemIdMap': {637: 632,
   924: 912,
   29: 28,
   1199: 1181,
   2019: 1950,
   3510: 3441,
   3882: 3812,
   3000: 2931,
   1090: 1074,
   3359: 3290}},
 {'UserID': 839,
  'TestMovies': [3659,
   1186,
   3827,
   3744,
   741,
   1097,
   2287,
   1472,
   2357,
   69,
   3556,
   909,
   750,
   2280,
   954],
  'NoWatched': [],
  'UserIdMap': {839: 838},
  'ItemIdMap': {3659: 3590,
   1186: 1169,
   3827: 3757,
   3744: 3675,
   741: 731,
   1097: 1081,
   2287: 2218,
   1472: 1444,
   2357: 2288,
   69: 68,
   3556: 3487,
   909: 897,
   750: 740,
   2280: 2211,
   954: 942}},
 {'UserID': 869,
  'TestMovies': [2374, 267, 486, 2016, 1014, 88, 432, 603, 153, 3669],
  'NoWatched': [],
  'UserIdMap': {869: 868},
  'ItemIdMap': {2374: 2305,
   267: 264,
   486: 482,
   2016: 1947,
   1014: 1001,
   88: 87,
   432: 428,
   603: 599,
   153: 151,
   3669: 3600}},
 {'UserID': 881,
  'TestMovies': [1256,
   1244,
   3897,
   1276,
   513,
   1197,
   1269,
   1294,
   1079,
   3363,
   1968,
   2300,
   1259,
   2918,
   1288,
   2791,
   2243,
   2797],
  'NoWatched': [],
  'UserIdMap': {881: 880},
  'ItemIdMap': {1256: 1236,
   1244: 1224,
   3897: 3827,
   1276: 1256,
   513: 509,
   1197: 1179,
   1269: 1249,
   1294: 1274,
   1079: 1063,
   3363: 3294,
   1968: 1899,
   2300: 2231,
   1259: 1239,
   2918: 2849,
   1288: 1268,
   2791: 2722,
   2243: 2174,
   2797: 2728}},
 {'UserID': 889,
  'TestMovies': [2328,
   3838,
   2995,
   1342,
   2327,
   3661,
   2461,
   328,
   397,
   3919,
   2107,
   2515,
   1862,
   3047,
   3713],
  'NoWatched': [],
  'UserIdMap': {889: 888},
  'ItemIdMap': {2328: 2259,
   3838: 3768,
   2995: 2926,
   1342: 1321,
   2327: 2258,
   3661: 3592,
   2461: 2392,
   328: 324,
   397: 393,
   3919: 3849,
   2107: 2038,
   2515: 2446,
   1862: 1793,
   3047: 2978,
   3713: 3644}},
 {'UserID': 1010,
  'TestMovies': [2718,
   2861,
   2959,
   3510,
   3175,
   2688,
   2580,
   3752,
   2723,
   2396,
   904,
   2336,
   1284,
   2693,
   2712,
   2133],
  'NoWatched': [],
  'UserIdMap': {1010: 1009},
  'ItemIdMap': {2718: 2649,
   2861: 2792,
   2959: 2890,
   3510: 3441,
   3175: 3106,
   2688: 2619,
   2580: 2511,
   3752: 3683,
   2723: 2654,
   2396: 2327,
   904: 892,
   2336: 2267,
   1284: 1264,
   2693: 2624,
   2712: 2643,
   2133: 2064}},
 {'UserID': 1015,
  'TestMovies': [3952,
   2624,
   2594,
   3328,
   2240,
   2418,
   659,
   3298,
   1959,
   3157,
   2070],
  'NoWatched': [],
  'UserIdMap': {1015: 1014},
  'ItemIdMap': {3952: 3882,
   2624: 2555,
   2594: 2525,
   3328: 3259,
   2240: 2171,
   2418: 2349,
   659: 653,
   3298: 3229,
   1959: 1890,
   3157: 3088,
   2070: 2001}},
 {'UserID': 1019,
  'TestMovies': [3535,
   101,
   1262,
   2321,
   2872,
   3827,
   3633,
   3481,
   3006,
   334,
   337,
   1594,
   12],
  'NoWatched': [],
  'UserIdMap': {1019: 1018},
  'ItemIdMap': {3535: 3466,
   101: 99,
   1262: 1242,
   2321: 2252,
   2872: 2803,
   3827: 3757,
   3633: 3564,
   3481: 3412,
   3006: 2937,
   334: 330,
   337: 333,
   1594: 1553,
   12: 11}},
 {'UserID': 1051,
  'TestMovies': [2166, 3882, 2996, 2689, 988, 2966, 2891, 2167, 1350, 1333],
  'NoWatched': [],
  'UserIdMap': {1051: 1050},
  'ItemIdMap': {2166: 2097,
   3882: 3812,
   2996: 2927,
   2689: 2620,
   988: 976,
   2966: 2897,
   2891: 2822,
   2167: 2098,
   1350: 1329,
   1333: 1313}},
 {'UserID': 1088,
  'TestMovies': [943, 2019, 3171, 1201, 1120, 446, 154, 999, 3543, 2314, 1186],
  'NoWatched': [],
  'UserIdMap': {1088: 1087},
  'ItemIdMap': {943: 931,
   2019: 1950,
   3171: 3102,
   1201: 1183,
   1120: 1104,
   446: 442,
   154: 152,
   999: 986,
   3543: 3474,
   2314: 2245,
   1186: 1169}},
 {'UserID': 1117,
  'TestMovies': [2826,
   1835,
   1552,
   1183,
   3082,
   2165,
   597,
   3264,
   95,
   89,
   2393,
   3712,
   1287],
  'NoWatched': [],
  'UserIdMap': {1117: 1116},
  'ItemIdMap': {2826: 2757,
   1835: 1767,
   1552: 1513,
   1183: 1166,
   3082: 3013,
   2165: 2096,
   597: 593,
   3264: 3195,
   95: 93,
   89: 88,
   2393: 2324,
   3712: 3643,
   1287: 1267}},
 {'UserID': 1120,
  'TestMovies': [2890, 1302, 3317, 3624, 2770, 2009, 3831, 2714, 1884, 3287],
  'NoWatched': [],
  'UserIdMap': {1120: 1119},
  'ItemIdMap': {2890: 2821,
   1302: 1282,
   3317: 3248,
   3624: 3555,
   2770: 2701,
   2009: 1940,
   3831: 3761,
   2714: 2645,
   1884: 1815,
   3287: 3218}},
 {'UserID': 1150,
  'TestMovies': [3099,
   2104,
   1272,
   1201,
   2866,
   3461,
   3296,
   1940,
   3203,
   2204,
   1082,
   2137],
  'NoWatched': [],
  'UserIdMap': {1150: 1149},
  'ItemIdMap': {3099: 3030,
   2104: 2035,
   1272: 1252,
   1201: 1183,
   2866: 2797,
   3461: 3392,
   3296: 3227,
   1940: 1871,
   3203: 3134,
   2204: 2135,
   1082: 1066,
   2137: 2068}},
 {'UserID': 1181,
  'TestMovies': [172,
   1639,
   3125,
   190,
   1466,
   3593,
   2940,
   3327,
   2810,
   233,
   1274,
   159,
   1748,
   2110,
   1631,
   3949,
   522],
  'NoWatched': [],
  'UserIdMap': {1181: 1180},
  'ItemIdMap': {172: 170,
   1639: 1593,
   3125: 3056,
   190: 188,
   1466: 1439,
   3593: 3524,
   2940: 2871,
   3327: 3258,
   2810: 2741,
   233: 230,
   1274: 1254,
   159: 157,
   1748: 1696,
   2110: 2041,
   1631: 1588,
   3949: 3879,
   522: 518}},
 {'UserID': 1203,
  'TestMovies': [1289,
   950,
   3503,
   1097,
   916,
   2947,
   2797,
   933,
   2990,
   1375,
   2054,
   3952,
   3949],
  'NoWatched': [],
  'UserIdMap': {1203: 1202},
  'ItemIdMap': {1289: 1269,
   950: 938,
   3503: 3434,
   1097: 1081,
   916: 904,
   2947: 2878,
   2797: 2728,
   933: 921,
   2990: 2921,
   1375: 1354,
   2054: 1985,
   3952: 3882,
   3949: 3879}},
 {'UserID': 1264,
  'TestMovies': [162,
   1123,
   1310,
   1189,
   3007,
   1649,
   2693,
   1012,
   3213,
   1017,
   2759,
   2712,
   785,
   2723,
   1513,
   2762],
  'NoWatched': [],
  'UserIdMap': {1264: 1263},
  'ItemIdMap': {162: 160,
   1123: 1107,
   1310: 1290,
   1189: 1172,
   3007: 2938,
   1649: 1603,
   2693: 2624,
   1012: 999,
   3213: 3144,
   1017: 1004,
   2759: 2690,
   2712: 2643,
   785: 775,
   2723: 2654,
   1513: 1478,
   2762: 2693}},
 {'UserID': 1266,
  'TestMovies': [593, 1982, 1732, 1251, 1944, 645, 412, 3528, 101, 154, 2579],
  'NoWatched': [],
  'UserIdMap': {1266: 1265},
  'ItemIdMap': {593: 589,
   1982: 1913,
   1732: 1683,
   1251: 1231,
   1944: 1875,
   645: 640,
   412: 408,
   3528: 3459,
   101: 99,
   154: 152,
   2579: 2510}},
 {'UserID': 1285,
  'TestMovies': [2459,
   2367,
   919,
   2648,
   1340,
   920,
   2366,
   2644,
   2633,
   3539,
   3300,
   1619,
   3039,
   2401],
  'NoWatched': [],
  'UserIdMap': {1285: 1284},
  'ItemIdMap': {2459: 2390,
   2367: 2298,
   919: 907,
   2648: 2579,
   1340: 1319,
   920: 908,
   2366: 2297,
   2644: 2575,
   2633: 2564,
   3539: 3470,
   3300: 3231,
   1619: 1576,
   3039: 2970,
   2401: 2332}},
 {'UserID': 1317,
  'TestMovies': [1096,
   1663,
   3098,
   3039,
   3101,
   3036,
   2420,
   2115,
   3529,
   2942,
   1827,
   2990,
   3791,
   1962],
  'NoWatched': [],
  'UserIdMap': {1317: 1316},
  'ItemIdMap': {1096: 1080,
   1663: 1617,
   3098: 3029,
   3039: 2970,
   3101: 3032,
   3036: 2967,
   2420: 2351,
   2115: 2046,
   3529: 3460,
   2942: 2873,
   1827: 1760,
   2990: 2921,
   3791: 3722,
   1962: 1893}},
 {'UserID': 1340,
  'TestMovies': [3869,
   337,
   366,
   2297,
   383,
   1548,
   454,
   3298,
   3745,
   3535,
   2902,
   1371,
   293,
   3000,
   1754],
  'NoWatched': [],
  'UserIdMap': {1340: 1339},
  'ItemIdMap': {3869: 3799,
   337: 333,
   366: 362,
   2297: 2228,
   383: 379,
   1548: 1509,
   454: 450,
   3298: 3229,
   3745: 3676,
   3535: 3466,
   2902: 2833,
   1371: 1350,
   293: 290,
   3000: 2931,
   1754: 1701}},
 {'UserID': 1383,
  'TestMovies': [3554, 3006, 746, 2155, 3598, 2959, 3952, 3357, 1267, 111],
  'NoWatched': [],
  'UserIdMap': {1383: 1382},
  'ItemIdMap': {3554: 3485,
   3006: 2937,
   746: 736,
   2155: 2086,
   3598: 3529,
   2959: 2890,
   3952: 3882,
   3357: 3288,
   1267: 1247,
   111: 109}},
 {'UserID': 1422,
  'TestMovies': [3948,
   3784,
   553,
   3806,
   3654,
   3360,
   1513,
   1252,
   3044,
   2662,
   2454,
   2300,
   1500,
   2966],
  'NoWatched': [],
  'UserIdMap': {1422: 1421},
  'ItemIdMap': {3948: 3878,
   3784: 3715,
   553: 549,
   3806: 3737,
   3654: 3585,
   3360: 3291,
   1513: 1478,
   1252: 1232,
   3044: 2975,
   2662: 2593,
   2454: 2385,
   2300: 2231,
   1500: 1468,
   2966: 2897}},
 {'UserID': 1425,
  'TestMovies': [529,
   1223,
   968,
   918,
   3882,
   627,
   3146,
   296,
   3089,
   3186,
   3480,
   1464,
   2221,
   3671],
  'NoWatched': [],
  'UserIdMap': {1425: 1424},
  'ItemIdMap': {529: 525,
   1223: 1205,
   968: 956,
   918: 906,
   3882: 3812,
   627: 622,
   3146: 3077,
   296: 293,
   3089: 3020,
   3186: 3117,
   3480: 3411,
   1464: 1437,
   2221: 2152,
   3671: 3602}},
 {'UserID': 1447,
  'TestMovies': [2917,
   2391,
   37,
   1255,
   904,
   3551,
   3735,
   162,
   3823,
   493,
   2300,
   1958,
   3114,
   29,
   1615],
  'NoWatched': [],
  'UserIdMap': {1447: 1446},
  'ItemIdMap': {2917: 2848,
   2391: 2322,
   37: 36,
   1255: 1235,
   904: 892,
   3551: 3482,
   3735: 3666,
   162: 160,
   3823: 3753,
   493: 489,
   2300: 2231,
   1958: 1889,
   3114: 3045,
   29: 28,
   1615: 1573}},
 {'UserID': 1448,
  'TestMovies': [1715,
   1651,
   117,
   3115,
   3578,
   3182,
   2912,
   2019,
   3189,
   3858,
   2542,
   1635],
  'NoWatched': [],
  'UserIdMap': {1448: 1447},
  'ItemIdMap': {1715: 1666,
   1651: 1605,
   117: 115,
   3115: 3046,
   3578: 3509,
   3182: 3113,
   2912: 2843,
   2019: 1950,
   3189: 3120,
   3858: 3788,
   2542: 2473,
   1635: 1591}},
 {'UserID': 1449,
  'TestMovies': [2080, 3103, 1888, 362, 140, 3206, 3896, 1719, 3717, 3578],
  'NoWatched': [],
  'UserIdMap': {1449: 1448},
  'ItemIdMap': {2080: 2011,
   3103: 3034,
   1888: 1819,
   362: 358,
   140: 138,
   3206: 3137,
   3896: 3826,
   1719: 1670,
   3717: 3648,
   3578: 3509}},
 {'UserID': 1451,
  'TestMovies': [1957, 2132, 2848, 2069, 1302, 1682, 3198, 3498, 322, 2312],
  'NoWatched': [],
  'UserIdMap': {1451: 1450},
  'ItemIdMap': {1957: 1888,
   2132: 2063,
   2848: 2779,
   2069: 2000,
   1302: 1282,
   1682: 1636,
   3198: 3129,
   3498: 3429,
   322: 319,
   2312: 2243}},
 {'UserID': 1470,
  'TestMovies': [2421, 361, 2948, 1952, 457, 1584, 2141, 691, 1379, 52],
  'NoWatched': [],
  'UserIdMap': {1470: 1469},
  'ItemIdMap': {2421: 2352,
   361: 357,
   2948: 2879,
   1952: 1883,
   457: 453,
   1584: 1543,
   2141: 2072,
   691: 682,
   1379: 1358,
   52: 51}},
 {'UserID': 1579,
  'TestMovies': [3949,
   3330,
   3718,
   1278,
   2273,
   2046,
   1247,
   916,
   3147,
   231,
   493,
   3683,
   2953,
   922],
  'NoWatched': [],
  'UserIdMap': {1579: 1578},
  'ItemIdMap': {3949: 3879,
   3330: 3261,
   3718: 3649,
   1278: 1258,
   2273: 2204,
   2046: 1977,
   1247: 1227,
   916: 904,
   3147: 3078,
   231: 228,
   493: 489,
   3683: 3614,
   2953: 2884,
   922: 910}},
 {'UserID': 1605,
  'TestMovies': [299,
   1594,
   1629,
   3051,
   2806,
   3863,
   3429,
   2837,
   2891,
   2029,
   29,
   2583,
   2348,
   2594,
   3330,
   443],
  'NoWatched': [],
  'UserIdMap': {1605: 1604},
  'ItemIdMap': {299: 296,
   1594: 1553,
   1629: 1586,
   3051: 2982,
   2806: 2737,
   3863: 3793,
   3429: 3360,
   2837: 2768,
   2891: 2822,
   2029: 1960,
   29: 28,
   2583: 2514,
   2348: 2279,
   2594: 2525,
   3330: 3261,
   443: 439}},
 {'UserID': 1613,
  'TestMovies': [1032,
   1019,
   932,
   1016,
   923,
   912,
   2018,
   930,
   1282,
   596,
   953,
   2176,
   1029,
   919,
   1927,
   965,
   2366,
   594,
   3629],
  'NoWatched': [],
  'UserIdMap': {1613: 1612},
  'ItemIdMap': {1032: 1019,
   1019: 1006,
   932: 920,
   1016: 1003,
   923: 911,
   912: 900,
   2018: 1949,
   930: 918,
   1282: 1262,
   596: 592,
   953: 941,
   2176: 2107,
   1029: 1016,
   919: 907,
   1927: 1858,
   965: 953,
   2366: 2297,
   594: 590,
   3629: 3560}},
 {'UserID': 1632,
  'TestMovies': [538,
   30,
   1682,
   300,
   3181,
   515,
   16,
   1466,
   2283,
   3720,
   3328,
   3952,
   3320,
   3618,
   918,
   1230],
  'NoWatched': [],
  'UserIdMap': {1632: 1631},
  'ItemIdMap': {538: 534,
   30: 29,
   1682: 1636,
   300: 297,
   3181: 3112,
   515: 511,
   16: 15,
   1466: 1439,
   2283: 2214,
   3720: 3651,
   3328: 3259,
   3952: 3882,
   3320: 3251,
   3618: 3549,
   918: 906,
   1230: 1211}},
 {'UserID': 1635,
  'TestMovies': [24,
   2060,
   2059,
   3208,
   2120,
   1911,
   1588,
   1756,
   184,
   3071,
   3405,
   1693],
  'NoWatched': [],
  'UserIdMap': {1635: 1634},
  'ItemIdMap': {24: 23,
   2060: 1991,
   2059: 1990,
   3208: 3139,
   2120: 2051,
   1911: 1842,
   1588: 1547,
   1756: 1703,
   184: 182,
   3071: 3002,
   3405: 3336,
   1693: 1646}},
 {'UserID': 1647,
  'TestMovies': [3901,

In [ ]:
metrics.is_tp(df_item_similarities, [1], 2, 0.8)

False

In [ ]:
# for i in test:
#     i['NoWatched'] = list(set(movies['MovieID'].unique()).difference(set(ratings_train[ratings_train['UserID'] == i['UserID']]["MovieID"].values)))

In [ ]:
test[0]['ItemIdMap']

{950: 938,
 1090: 1074,
 3658: 3589,
 1949: 1880,
 2587: 2518,
 632: 627,
 3746: 3677,
 1254: 1234,
 3007: 2938,
 1301: 1281}

In [ ]:
user_id_map

{1: 0,
 2: 1,
 3: 2,
 4: 3,
 5: 4,
 6: 5,
 7: 6,
 8: 7,
 9: 8,
 10: 9,
 11: 10,
 12: 11,
 13: 12,
 14: 13,
 15: 14,
 16: 15,
 17: 16,
 18: 17,
 19: 18,
 20: 19,
 21: 20,
 22: 21,
 23: 22,
 24: 23,
 25: 24,
 26: 25,
 27: 26,
 28: 27,
 29: 28,
 30: 29,
 31: 30,
 32: 31,
 33: 32,
 34: 33,
 35: 34,
 36: 35,
 37: 36,
 38: 37,
 39: 38,
 40: 39,
 41: 40,
 42: 41,
 43: 42,
 44: 43,
 45: 44,
 46: 45,
 47: 46,
 48: 47,
 49: 48,
 50: 49,
 51: 50,
 52: 51,
 53: 52,
 54: 53,
 55: 54,
 56: 55,
 57: 56,
 58: 57,
 59: 58,
 60: 59,
 61: 60,
 62: 61,
 63: 62,
 64: 63,
 65: 64,
 66: 65,
 67: 66,
 68: 67,
 69: 68,
 70: 69,
 71: 70,
 72: 71,
 73: 72,
 74: 73,
 75: 74,
 76: 75,
 77: 76,
 78: 77,
 79: 78,
 80: 79,
 81: 80,
 82: 81,
 83: 82,
 84: 83,
 85: 84,
 86: 85,
 87: 86,
 88: 87,
 89: 88,
 90: 89,
 91: 90,
 92: 91,
 93: 92,
 94: 93,
 95: 94,
 96: 95,
 97: 96,
 98: 97,
 99: 98,
 100: 99,
 101: 100,
 102: 101,
 103: 102,
 104: 103,
 105: 104,
 106: 105,
 107: 106,
 108: 107,
 109: 108,
 110: 109,
 111: 110,
 112: 111,
 113: 112,
 114: 113,
 115: 114,
 116: 115,
 117: 116,
 118: 117,
 119: 118,
 120: 119,
 121: 120,
 122: 121,
 123: 122,
 124: 123,
 125: 124,
 126: 125,
 127: 126,
 128: 127,
 129: 128,
 130: 129,
 131: 130,
 132: 131,
 133: 132,
 134: 133,
 135: 134,
 136: 135,
 137: 136,
 138: 137,
 139: 138,
 140: 139,
 141: 140,
 142: 141,
 143: 142,
 144: 143,
 145: 144,
 146: 145,
 147: 146,
 148: 147,
 149: 148,
 150: 149,
 151: 150,
 152: 151,
 153: 152,
 154: 153,
 155: 154,
 156: 155,
 157: 156,
 158: 157,
 159: 158,
 160: 159,
 161: 160,
 162: 161,
 163: 162,
 164: 163,
 165: 164,
 166: 165,
 167: 166,
 168: 167,
 169: 168,
 170: 169,
 171: 170,
 172: 171,
 173: 172,
 174: 173,
 175: 174,
 176: 175,
 177: 176,
 178: 177,
 179: 178,
 180: 179,
 181: 180,
 182: 181,
 183: 182,
 184: 183,
 185: 184,
 186: 185,
 187: 186,
 188: 187,
 189: 188,
 190: 189,
 191: 190,
 192: 191,
 193: 192,
 194: 193,
 195: 194,
 196: 195,
 197: 196,
 198: 197,
 199: 198,
 200: 199,
 201: 200,
 202: 201,
 203: 202,
 204: 203,
 205: 204,
 206: 205,
 207: 206,
 208: 207,
 209: 208,
 210: 209,
 211: 210,
 212: 211,
 213: 212,
 214: 213,
 215: 214,
 216: 215,
 217: 216,
 218: 217,
 219: 218,
 220: 219,
 221: 220,
 222: 221,
 223: 222,
 224: 223,
 225: 224,
 226: 225,
 227: 226,
 228: 227,
 229: 228,
 230: 229,
 231: 230,
 232: 231,
 233: 232,
 234: 233,
 235: 234,
 236: 235,
 237: 236,
 238: 237,
 239: 238,
 240: 239,
 241: 240,
 242: 241,
 243: 242,
 244: 243,
 245: 244,
 246: 245,
 247: 246,
 248: 247,
 249: 248,
 250: 249,
 251: 250,
 252: 251,
 253: 252,
 254: 253,
 255: 254,
 256: 255,
 257: 256,
 258: 257,
 259: 258,
 260: 259,
 261: 260,
 262: 261,
 263: 262,
 264: 263,
 265: 264,
 266: 265,
 267: 266,
 268: 267,
 269: 268,
 270: 269,
 271: 270,
 272: 271,
 273: 272,
 274: 273,
 275: 274,
 276: 275,
 277: 276,
 278: 277,
 279: 278,
 280: 279,
 281: 280,
 282: 281,
 283: 282,
 284: 283,
 285: 284,
 286: 285,
 287: 286,
 288: 287,
 289: 288,
 290: 289,
 291: 290,
 292: 291,
 293: 292,
 294: 293,
 295: 294,
 296: 295,
 297: 296,
 298: 297,
 299: 298,
 300: 299,
 301: 300,
 302: 301,
 303: 302,
 304: 303,
 305: 304,
 306: 305,
 307: 306,
 308: 307,
 309: 308,
 310: 309,
 311: 310,
 312: 311,
 313: 312,
 314: 313,
 315: 314,
 316: 315,
 317: 316,
 318: 317,
 319: 318,
 320: 319,
 321: 320,
 322: 321,
 323: 322,
 324: 323,
 325: 324,
 326: 325,
 327: 326,
 328: 327,
 329: 328,
 330: 329,
 331: 330,
 332: 331,
 333: 332,
 334: 333,
 335: 334,
 336: 335,
 337: 336,
 338: 337,
 339: 338,
 340: 339,
 341: 340,
 342: 341,
 343: 342,
 344: 343,
 345: 344,
 346: 345,
 347: 346,
 348: 347,
 349: 348,
 350: 349,
 351: 350,
 352: 351,
 353: 352,
 354: 353,
 355: 354,
 356: 355,
 357: 356,
 358: 357,
 359: 358,
 360: 359,
 361: 360,
 362: 361,
 363: 362,
 364: 363,
 365: 364,
 366: 365,
 367: 366,
 368: 367,
 369: 368,
 370: 369,
 371: 370,
 372: 371,
 373: 372,
 374: 373,
 375: 374,
 376: 375,
 377: 376,
 378: 377,
 379: 378,
 380: 379,
 381: 380,
 382: 381,
 383: 382,
 384: 383,
 385: 384,
 386: 385,
 387: 386,
 388: 387,
 389: 388,
 390: 389,
 391: 390,
 392: 391,
 393: 392,
 394: 393,
 395: 394,
 396: 395,
 397: 396,
 398: 397,
 399: 398,
 400: 399,
 401: 400,
 402: 401,
 403: 402,
 404: 403,
 405: 404,
 406: 405,
 407: 406,
 408: 407,
 409: 408,
 410: 409,
 411: 410,
 412: 411,
 413: 412,
 414: 413,
 415: 414,
 416: 415,
 417: 416,
 418: 417,
 419: 418,
 420: 419,
 421: 420,
 422: 421,
 423: 422,
 424: 423,
 425: 424,
 426: 425,
 427: 426,
 428: 427,
 429: 428,
 430: 429,
 431: 430,
 432: 431,
 433: 432,
 434: 433,
 435: 434,
 436: 435,
 437: 436,
 438: 437,
 439: 438,
 440: 439,
 441: 440,
 442: 441,
 443: 442,
 444: 443,
 445: 444,
 446: 445,
 447: 446,
 448: 447,
 449: 448,
 450: 449,
 451: 450,
 452: 451,
 453: 452,
 454: 453,
 455: 454,
 456: 455,
 457: 456,
 458: 457,
 459: 458,
 460: 459,
 461: 460,
 462: 461,
 463: 462,
 464: 463,
 465: 464,
 466: 465,
 467: 466,
 468: 467,
 469: 468,
 470: 469,
 471: 470,
 472: 471,
 473: 472,
 474: 473,
 475: 474,
 476: 475,
 477: 476,
 478: 477,
 479: 478,
 480: 479,
 481: 480,
 482: 481,
 483: 482,
 484: 483,
 485: 484,
 486: 485,
 487: 486,
 488: 487,
 489: 488,
 490: 489,
 491: 490,
 492: 491,
 493: 492,
 494: 493,
 495: 494,
 496: 495,
 497: 496,
 498: 497,
 499: 498,
 500: 499,
 501: 500,
 502: 501,
 503: 502,
 504: 503,
 505: 504,
 506: 505,
 507: 506,
 508: 507,
 509: 508,
 510: 509,
 511: 510,
 512: 511,
 513: 512,
 514: 513,
 515: 514,
 516: 515,
 517: 516,
 518: 517,
 519: 518,
 520: 519,
 521: 520,
 522: 521,
 523: 522,
 524: 523,
 525: 524,
 526: 525,
 527: 526,
 528: 527,
 529: 528,
 530: 529,
 531: 530,
 532: 531,
 533: 532,
 534: 533,
 535: 534,
 536: 535,
 537: 536,
 538: 537,
 539: 538,
 540: 539,
 541: 540,
 542: 541,
 543: 542,
 544: 543,
 545: 544,
 546: 545,
 547: 546,
 548: 547,
 549: 548,
 550: 549,
 551: 550,
 552: 551,
 553: 552,
 554: 553,
 555: 554,
 556: 555,
 557: 556,
 558: 557,
 559: 558,
 560: 559,
 561: 560,
 562: 561,
 563: 562,
 564: 563,
 565: 564,
 566: 565,
 567: 566,
 568: 567,
 569: 568,
 570: 569,
 571: 570,
 572: 571,
 573: 572,
 574: 573,
 575: 574,
 576: 575,
 577: 576,
 578: 577,
 579: 578,
 580: 579,
 581: 580,
 582: 581,
 583: 582,
 584: 583,
 585: 584,
 586: 585,
 587: 586,
 588: 587,
 589: 588,
 590: 589,
 591: 590,
 592: 591,
 593: 592,
 594: 593,
 595: 594,
 596: 595,
 597: 596,
 598: 597,
 599: 598,
 600: 599,
 601: 600,
 602: 601,
 603: 602,
 604: 603,
 605: 604,
 606: 605,
 607: 606,
 608: 607,
 609: 608,
 610: 609,
 611: 610,
 612: 611,
 613: 612,
 614: 613,
 615: 614,
 616: 615,
 617: 616,
 618: 617,
 619: 618,
 620: 619,
 621: 620,
 622: 621,
 623: 622,
 624: 623,
 625: 624,
 626: 625,
 627: 626,
 628: 627,
 629: 628,
 630: 629,
 631: 630,
 632: 631,
 633: 632,
 634: 633,
 635: 634,
 636: 635,
 637: 636,
 638: 637,
 639: 638,
 640: 639,
 641: 640,
 642: 641,
 643: 642,
 644: 643,
 645: 644,
 646: 645,
 647: 646,
 648: 647,
 649: 648,
 650: 649,
 651: 650,
 652: 651,
 653: 652,
 654: 653,
 655: 654,
 656: 655,
 657: 656,
 658: 657,
 659: 658,
 660: 659,
 661: 660,
 662: 661,
 663: 662,
 664: 663,
 665: 664,
 666: 665,
 667: 666,
 668: 667,
 669: 668,
 670: 669,
 671: 670,
 672: 671,
 673: 672,
 674: 673,
 675: 674,
 676: 675,
 677: 676,
 678: 677,
 679: 678,
 680: 679,
 681: 680,
 682: 681,
 683: 682,
 684: 683,
 685: 684,
 686: 685,
 687: 686,
 688: 687,
 689: 688,
 690: 689,
 691: 690,
 692: 691,
 693: 692,
 694: 693,
 695: 694,
 696: 695,
 697: 696,
 698: 697,
 699: 698,
 700: 699,
 701: 700,
 702: 701,
 703: 702,
 704: 703,
 705: 704,
 706: 705,
 707: 706,
 708: 707,
 709: 708,
 710: 709,
 711: 710,
 712: 711,
 713: 712,
 714: 713,
 715: 714,
 716: 715,
 717: 716,
 718: 717,
 719: 718,
 720: 719,
 721: 720,
 722: 721,
 723: 722,
 724: 723,
 725: 724,
 726: 725,
 727: 726,
 728: 727,
 729: 728,
 730: 729,
 731: 730,
 732: 731,
 733: 732,
 734: 733,
 735: 734,
 736: 735,
 737: 736,
 738: 737,
 739: 738,
 740: 739,
 741: 740,
 742: 741,
 743: 742,
 744: 743,
 745: 744,
 746: 745,
 747: 746,
 748: 747,
 749: 748,
 750: 749,
 751: 750,
 752: 751,
 753: 752,
 754: 753,
 755: 754,
 756: 755,
 757: 756,
 758: 757,
 759: 758,
 760: 759,
 761: 760,
 762: 761,
 763: 762,
 764: 763,
 765: 764,
 766: 765,
 767: 766,
 768: 767,
 769: 768,
 770: 769,
 771: 770,
 772: 771,
 773: 772,
 774: 773,
 775: 774,
 776: 775,
 777: 776,
 778: 777,
 779: 778,
 780: 779,
 781: 780,
 782: 781,
 783: 782,
 784: 783,
 785: 784,
 786: 785,
 787: 786,
 788: 787,
 789: 788,
 790: 789,
 791: 790,
 792: 791,
 793: 792,
 794: 793,
 795: 794,
 796: 795,
 797: 796,
 798: 797,
 799: 798,
 800: 799,
 801: 800,
 802: 801,
 803: 802,
 804: 803,
 805: 804,
 806: 805,
 807: 806,
 808: 807,
 809: 808,
 810: 809,
 811: 810,
 812: 811,
 813: 812,
 814: 813,
 815: 814,
 816: 815,
 817: 816,
 818: 817,
 819: 818,
 820: 819,
 821: 820,
 822: 821,
 823: 822,
 824: 823,
 825: 824,
 826: 825,
 827: 826,
 828: 827,
 829: 828,
 830: 829,
 831: 830,
 832: 831,
 833: 832,
 834: 833,
 835: 834,
 836: 835,
 837: 836,
 838: 837,
 839: 838,
 840: 839,
 841: 840,
 842: 841,
 843: 842,
 844: 843,
 845: 844,
 846: 845,
 847: 846,
 848: 847,
 849: 848,
 850: 849,
 851: 850,
 852: 851,
 853: 852,
 854: 853,
 855: 854,
 856: 855,
 857: 856,
 858: 857,
 859: 858,
 860: 859,
 861: 860,
 862: 861,
 863: 862,
 864: 863,
 865: 864,
 866: 865,
 867: 866,
 868: 867,
 869: 868,
 870: 869,
 871: 870,
 872: 871,
 873: 872,
 874: 873,
 875: 874,
 876: 875,
 877: 876,
 878: 877,
 879: 878,
 880: 879,
 881: 880,
 882: 881,
 883: 882,
 884: 883,
 885: 884,
 886: 885,
 887: 886,
 888: 887,
 889: 888,
 890: 889,
 891: 890,
 892: 891,
 893: 892,
 894: 893,
 895: 894,
 896: 895,
 897: 896,
 898: 897,
 899: 898,
 900: 899,
 901: 900,
 902: 901,
 903: 902,
 904: 903,
 905: 904,
 906: 905,
 907: 906,
 908: 907,
 909: 908,
 910: 909,
 911: 910,
 912: 911,
 913: 912,
 914: 913,
 915: 914,
 916: 915,
 917: 916,
 918: 917,
 919: 918,
 920: 919,
 921: 920,
 922: 921,
 923: 922,
 924: 923,
 925: 924,
 926: 925,
 927: 926,
 928: 927,
 929: 928,
 930: 929,
 931: 930,
 932: 931,
 933: 932,
 934: 933,
 935: 934,
 936: 935,
 937: 936,
 938: 937,
 939: 938,
 940: 939,
 941: 940,
 942: 941,
 943: 942,
 944: 943,
 945: 944,
 946: 945,
 947: 946,
 948: 947,
 949: 948,
 950: 949,
 951: 950,
 952: 951,
 953: 952,
 954: 953,
 955: 954,
 956: 955,
 957: 956,
 958: 957,
 959: 958,
 960: 959,
 961: 960,
 962: 961,
 963: 962,
 964: 963,
 965: 964,
 966: 965,
 967: 966,
 968: 967,
 969: 968,
 970: 969,
 971: 970,
 972: 971,
 973: 972,
 974: 973,
 975: 974,
 976: 975,
 977: 976,
 978: 977,
 979: 978,
 980: 979,
 981: 980,
 982: 981,
 983: 982,
 984: 983,
 985: 984,
 986: 985,
 987: 986,
 988: 987,
 989: 988,
 990: 989,
 991: 990,
 992: 991,
 993: 992,
 994: 993,
 995: 994,
 996: 995,
 997: 996,
 998: 997,
 999: 998,
 1000: 999,
 ...}

In [ ]:
sm_item_features

<3883x3901 sparse matrix of type '<class 'numpy.float32'>'
	with 10291 stored elements in Compressed Sparse Row format>

In [ ]:
# for i in tqdm(test):
#     list_scores = model.predict(i['UserIdMap'][i["UserID"]], list(item_id_map.values()))
#     series_scores = pd.Series(list_scores)
#     series_scores.index = item_id_map.keys()
#     series_scores.sort_values(ascending=False, inplace=True)
#     predictions = series_scores
#     top_p = []
#     for idx in predictions.index:
#         if ratings_train[(ratings_train['UserID'] == i["UserID"]) & (ratings_train['MovieID'] == idx)]['UserID'].sum():   
#             continue
#         top_p.append(idx)
#         if len(top_p) >= TAKE_FIRST_PREDICT:
#             break
#     tmp_c = 0
#     for j in top_p:
#         if metrics.is_tp(df_item_similarities, i["TestMovies"], j, 0.7):
#             tmp_c += 1
#     i['tp'] = tmp_c
#     i['tn'] = len(top_p) - tmp_c


for i in tqdm(test):
    i['tpIdxs'] = []
    list_scores = model.predict(i['UserIdMap'][i["UserID"]], list(item_id_map.values()), item_features=sparse_movies_features, user_features=sparse_user_features)
    series_scores = pd.Series(list_scores)
    series_scores.index = item_id_map.keys()
    series_scores.sort_values(ascending=False, inplace=True)
    predictions = series_scores
    top_p = []
    for idx in predictions.index:
        if ratings_train[(ratings_train['UserID'] == i["UserID"]) & (ratings_train['MovieID'] == idx)]['UserID'].sum():   
            continue
        top_p.append(idx)
        if len(top_p) >= TAKE_FIRST_PREDICT:
            break
    tmp_c = 0
    for idx, j in enumerate(top_p):
        if metrics.is_tp(df_item_similarities, i["TestMovies"], j, SIM_K):
            tmp_c += 1
            i['tpIdxs'].append(idx + 1)
    i['tp'] = tmp_c
    i['tn'] = len(top_p) - tmp_c

100%|██████████| 2945/2945 [11:34<00:00,  4.24it/s]

## Оценка

#### Встроенные метрики

In [ ]:
test_auc = auc_score(model, sm_test_interactions, train_interactions=sm_train_interactions,user_features=sparse_user_features,
                             item_features=sparse_movies_features, num_threads=2).mean()
print('Collaborative filtering test AUC: %s' % test_auc)

Collaborative filtering test AUC: 0.65638024

In [ ]:
np_arr_prec = precision_at_k(model,
                             test_interactions=sm_test_interactions,
                             user_features=sparse_user_features,
                             item_features=sparse_movies_features)
mapk = np_arr_prec.mean()
print('Collaborative filtering test mapk: %s' % mapk)

Collaborative filtering test mapk: 0.0567742

#### Кастомные

In [ ]:
sim_acc = []
for i in test:
    sim_acc.append(i['tp'] / TAKE_FIRST_PREDICT)
sim_acc = np.mean(sim_acc)
print('Collaborative filtering test sim acc mean: %s' % sim_acc)

Collaborative filtering test sim acc mean: 0.6921833616298811

In [ ]:
test[0]['tpIdxs']

[14, 16, 25, 35, 44, 45, 46, 51, 56, 59, 69, 78, 79, 85, 89, 94, 98]

In [ ]:
sim_acc_rank = []
for row in test:
    n = 0
    tmp_sum = 0
    for i in range(K_TO_PRED):
        if i + 1 in row['tpIdxs']:
            n += 1
        tmp_sum += n / (i + 1)
    tmp_sum = tmp_sum / K_TO_PRED
    sim_acc_rank.append(tmp_sum)
sim_acc_rank_mean = np.mean(sim_acc_rank)
print('Collaborative filtering test sim acc rank mean: %s' % sim_acc_rank_mean)

Collaborative filtering test sim acc rank mean: 0.7053730553980239

## Популярные фильмы

In [ ]:
ratings_train['MovieID'].value_counts()

MovieID
1196    2083
2858    2003
260     1966
1210    1895
2571    1870
        ...
3312       1
3621       1
142        1
2742       1
1842       1
Name: count, Length: 3666, dtype: int64

In [ ]:
for i in tqdm(test):
    i['tpIdxs'] = []
    predictions = ratings_train['MovieID'].value_counts()
    top_p = []
    for idx in predictions.index:
        if ratings_train[(ratings_train['UserID'] == i["UserID"]) & (ratings_train['MovieID'] == idx)]['UserID'].sum():   
            continue
        top_p.append(idx)
        if len(top_p) >= TAKE_FIRST_PREDICT:
            break
    tmp_c = 0
    for idx, j in enumerate(top_p):
        if metrics.is_tp(df_item_similarities, i["TestMovies"], j, SIM_K):
            tmp_c += 1
            i['tpIdxs'].append(idx + 1)
    i['tp'] = tmp_c
    i['tn'] = len(top_p) - tmp_c

100%|██████████| 2945/2945 [16:22<00:00,  3.00it/s]

In [ ]:
sim_acc = []
for i in test:
    sim_acc.append(i['tp'] / TAKE_FIRST_PREDICT)
sim_acc = np.mean(sim_acc)
print('Collaborative filtering test sim acc mean: %s' % sim_acc)

Collaborative filtering test sim acc mean: 0.7080882852292021

In [ ]:
sim_acc_rank = []
for row in test:
    n = 0
    tmp_sum = 0
    for i in range(K_TO_PRED):
        if i + 1 in row['tpIdxs']:
            n += 1
        tmp_sum += n / (i + 1)
    tmp_sum = tmp_sum / K_TO_PRED
    sim_acc_rank.append(tmp_sum)
sim_acc_rank_mean = np.mean(sim_acc_rank)
print('Collaborative filtering test sim acc rank mean: %s' % sim_acc_rank_mean)

Collaborative filtering test sim acc rank mean: 0.7124445347026322